<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\Source\WebProjects\leapy\static\models\bday.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import {AlwaysDepth, EqualDepth, GreaterDepth, Group, LessEqualDepth, NeverDepth} from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/bday.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  gltf.then((model) => {
    function alphaFix(material) {
      material.transparent = true;
      material.alphaToCoverage = true;
      material.depthFunc = LessEqualDepth;
      material.depthTest = false;
      material.depthWrite = false;
    }
    alphaFix(model.materials['Material'])
    alphaFix(model.materials['lambert10'])
    alphaFix(model.materials['lambert11'])
    alphaFix(model.materials['lambert12'])
    console.log()
  });

  $: $actions['Take 001']?.play();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.85}>
        <T.Group name="e3bc1e39c3a640d4a6dab07a1629c6d8fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="polySurface013"
                position={[2.14, 4.45, 5.32]}
                rotation={[0.02, -0.92, 0.4]}
                scale={[1, 0.74, 1]}
              >
                <T.Mesh
                  name="polySurface013_lambert11_0"
                  geometry={gltf.nodes.polySurface013_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface018" position={[-3.81, 9.42, -3.93]} scale={0.24}>
                <T.Mesh
                  name="polySurface018_lambert12_0"
                  geometry={gltf.nodes.polySurface018_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface024" position={[-2.93, 3.23, -0.63]} rotation={[0.37, 0.85, 0.07]}>
                <T.Mesh
                  name="polySurface024_lambert10_0"
                  geometry={gltf.nodes.polySurface024_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface031"
                position={[-5.37, 3.85, -3.69]}
                rotation={[1.6, -0.13, -3.11]}
                scale={[-1.74, -1.5, -1.4]}
              >
                <T.Mesh
                  name="polySurface031_lambert10_0"
                  geometry={gltf.nodes.polySurface031_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface040"
                position={[-9.88, 3.65, 6.68]}
                rotation={[1.73, -0.2, 0.25]}
                scale={[-1.22, -0.61, -0.44]}
              >
                <T.Mesh
                  name="polySurface040_lambert10_0"
                  geometry={gltf.nodes.polySurface040_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface041" position={[-11.73, 4.47, 1.09]} rotation={[0.51, 0.7, -0.08]} scale={0.55}>
                <T.Mesh
                  name="polySurface041_lambert10_0"
                  geometry={gltf.nodes.polySurface041_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface042"
                position={[-11.51, 4.47, 1.55]}
                rotation={[-2.46, 0.74, -2.82]}
                scale={0.3}
              >
                <T.Mesh
                  name="polySurface042_lambert10_0"
                  geometry={gltf.nodes.polySurface042_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface048" position={[-2.8, 10.58, 8.94]} rotation={[-0.73, -0.76, 0.53]}>
                <T.Mesh
                  name="polySurface048_lambert10_0"
                  geometry={gltf.nodes.polySurface048_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface050" position={[1.13, 8.68, 10.79]}>
                <T.Mesh
                  name="polySurface050_lambert10_0"
                  geometry={gltf.nodes.polySurface050_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface08"
                position={[-3.14, 3.53, -4.09]}
                rotation={[-0.15, 0.03, 0.22]}
                scale={[1, 0.64, 1]}
              >
                <T.Mesh
                  name="polySurface08_lambert11_0"
                  geometry={gltf.nodes.polySurface08_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="babase">
                <T.Mesh
                  name="1"
                  geometry={gltf.nodes['1'].geometry}
                  material={gltf.materials.lambert10}
                  morphTargetDictionary={gltf.nodes['1'].morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes['1'].morphTargetInfluences}
                />
              </T.Group>
              <T.Group name="base" position={[-2.11, 2.6, 3.3]} scale={9.44}>
                <T.Mesh
                  name="0"
                  geometry={gltf.nodes['0'].geometry}
                  material={gltf.materials.lambert11}
                  morphTargetDictionary={gltf.nodes['0'].morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes['0'].morphTargetInfluences}
                />
              </T.Group>
              <T.Group name="marmelad">
                <T.Group
                  name="polySurface0100"
                  position={[-2.19, 7.11, 4.9]}
                  rotation={[2.29, -1.29, 1.36]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0100_lambert12_0"
                    geometry={gltf.nodes.polySurface0100_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface0101"
                  position={[-3.75, 7.2, 3.06]}
                  rotation={[-2.15, 0.49, -2.45]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0101_lambert12_0"
                    geometry={gltf.nodes.polySurface0101_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface0102"
                  position={[6.37, 19.55, 0.38]}
                  rotation={[0.6, -0.51, 0.73]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0102_lambert12_0"
                    geometry={gltf.nodes.polySurface0102_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface0103" position={[-2.47, 8.04, 0.42]} rotation={[-2.75, 0, 1.64]} scale={2.03}>
                  <T.Mesh
                    name="polySurface0103_lambert12_0"
                    geometry={gltf.nodes.polySurface0103_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface0104"
                  position={[0.02, 13.15, 2.45]}
                  rotation={[-2.66, -0.64, 2.77]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0104_lambert12_0"
                    geometry={gltf.nodes.polySurface0104_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface0105" position={[7.54, 19.7, 0.23]} scale={2.03}>
                  <T.Mesh
                    name="polySurface0105_lambert12_0"
                    geometry={gltf.nodes.polySurface0105_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface0106"
                  position={[6.82, 19.6, -0.61]}
                  rotation={[-0.04, 0.37, 0.01]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0106_lambert12_0"
                    geometry={gltf.nodes.polySurface0106_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface0107" position={[6.4, 19.57, -1.15]} scale={2.03}>
                  <T.Mesh
                    name="polySurface0107_lambert12_0"
                    geometry={gltf.nodes.polySurface0107_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface0108"
                  position={[1.48, 17.56, 0.91]}
                  rotation={[1.54, 0.04, 2.19]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface0108_lambert12_0"
                    geometry={gltf.nodes.polySurface0108_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface0124" position={[-7.46, 6.65, 2.87]} rotation={[-0.34, 0.41, -0.28]} />
                <T.Group
                  name="polySurface0125"
                  position={[0.35, 9.19, -3.37]}
                  rotation={[-0.64, -0.02, 0.36]}
                  scale={2.8}
                >
                  <T.Mesh
                    name="polySurface0125_lambert10_0"
                    geometry={gltf.nodes.polySurface0125_lambert10_0.geometry}
                    material={gltf.materials.lambert10}
                  />
                </T.Group>
                <T.Group name="polySurface0128" position={[0.02, 6.03, 8.27]} rotation={[0.29, -0.04, 0.41]}>
                  <T.Mesh
                    name="polySurface0128_lambert10_0"
                    geometry={gltf.nodes.polySurface0128_lambert10_0.geometry}
                    material={gltf.materials.lambert10}
                  />
                </T.Group>
                <T.Group name="polySurface022" position={[-3.81, 7.87, -1.36]} scale={0.24}>
                  <T.Mesh
                    name="polySurface022_lambert12_0"
                    geometry={gltf.nodes.polySurface022_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface051"
                  position={[6.42, 19.6, -1.37]}
                  rotation={[0.06, 0.09, 0.06]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface051_lambert12_0"
                    geometry={gltf.nodes.polySurface051_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface052"
                  position={[1.92, 18.32, -0.05]}
                  rotation={[-0.88, 1.2, 0.85]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface052_lambert12_0"
                    geometry={gltf.nodes.polySurface052_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface053"
                  position={[-3.46, 0.61, 4.02]}
                  rotation={[-2.31, -0.41, 1.55]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface053_lambert12_0"
                    geometry={gltf.nodes.polySurface053_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface054"
                  position={[-4.9, -0.98, 1.57]}
                  rotation={[1.87, -1.2, 1.19]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface054_lambert12_0"
                    geometry={gltf.nodes.polySurface054_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface055"
                  position={[3.94, 19.19, 0.41]}
                  rotation={[-0.28, -0.84, 0.96]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface055_lambert12_0"
                    geometry={gltf.nodes.polySurface055_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface056"
                  position={[-5.67, 0.87, 3.62]}
                  rotation={[-1.38, -0.49, 1.95]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface056_lambert12_0"
                    geometry={gltf.nodes.polySurface056_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface057"
                  position={[-2.45, 10.1, 0.99]}
                  rotation={[-3.04, -0.71, 2.22]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface057_lambert12_0"
                    geometry={gltf.nodes.polySurface057_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface058"
                  position={[-5.97, 0.45, 0.88]}
                  rotation={[-2.78, 0.94, -1.54]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface058_lambert12_0"
                    geometry={gltf.nodes.polySurface058_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface059"
                  position={[-3.56, -0.17, 4.96]}
                  rotation={[-1.31, -0.46, 2.12]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface059_lambert12_0"
                    geometry={gltf.nodes.polySurface059_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface060"
                  position={[-5.13, 0.22, 3.54]}
                  rotation={[-1.35, -0.48, 2.01]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface060_lambert12_0"
                    geometry={gltf.nodes.polySurface060_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface061"
                  position={[-3.65, -1.35, 5.6]}
                  rotation={[1.31, -1.2, 0.59]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface061_lambert12_0"
                    geometry={gltf.nodes.polySurface061_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface062" position={[-5.35, 0.53, 3.72]} rotation={[2.21, 0.8, 2.26]} scale={2.03}>
                  <T.Mesh
                    name="polySurface062_lambert12_0"
                    geometry={gltf.nodes.polySurface062_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface063"
                  position={[1.18, 16.17, 0.4]}
                  rotation={[-1.98, 0.1, -3.04]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface063_lambert12_0"
                    geometry={gltf.nodes.polySurface063_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface064"
                  position={[-4.35, 0.61, 0.42]}
                  rotation={[-2.4, -0.11, 1.24]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface064_lambert12_0"
                    geometry={gltf.nodes.polySurface064_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface065"
                  position={[-3.46, 0.61, 4.02]}
                  rotation={[-2.31, -0.41, 1.55]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface065_lambert12_0"
                    geometry={gltf.nodes.polySurface065_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface066"
                  position={[2.83, 18.46, 2.48]}
                  rotation={[2.29, 1.49, -2.29]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface066_lambert12_0"
                    geometry={gltf.nodes.polySurface066_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface067" position={[4.16, 18.92, 0.59]} rotation={[0.7, 1.18, 1.41]} scale={2.03}>
                  <T.Mesh
                    name="polySurface067_lambert12_0"
                    geometry={gltf.nodes.polySurface067_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface068" position={[0.63, 17.2, 1.24]} rotation={[2.61, 0.91, 2.01]} scale={2.03}>
                  <T.Mesh
                    name="polySurface068_lambert12_0"
                    geometry={gltf.nodes.polySurface068_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface069"
                  position={[-5.59, 0.93, 1.71]}
                  rotation={[-1.5, -0.52, 1.71]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface069_lambert12_0"
                    geometry={gltf.nodes.polySurface069_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface070" position={[7.3, 19.44, -0.62]} scale={2.03}>
                  <T.Mesh
                    name="polySurface070_lambert12_0"
                    geometry={gltf.nodes.polySurface070_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface071" position={[-0.53, 15, 0.53]} rotation={[2.38, 0.13, -2.43]} scale={2.03}>
                  <T.Mesh
                    name="polySurface071_lambert12_0"
                    geometry={gltf.nodes.polySurface071_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface072"
                  position={[6.47, 19.57, -0.45]}
                  rotation={[0.37, -0.12, 0.34]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface072_lambert12_0"
                    geometry={gltf.nodes.polySurface072_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface073" position={[-4.9, 0.58, 1.57]} rotation={[1.87, -1.2, 1.19]} scale={2.03}>
                  <T.Mesh
                    name="polySurface073_lambert12_0"
                    geometry={gltf.nodes.polySurface073_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface074"
                  position={[0.92, 17.59, 0.55]}
                  rotation={[1.71, 0.83, 3.12]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface074_lambert12_0"
                    geometry={gltf.nodes.polySurface074_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface075"
                  position={[4.99, 19.38, -0.18]}
                  rotation={[0.43, 0.89, -0.34]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface075_lambert12_0"
                    geometry={gltf.nodes.polySurface075_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface076" position={[-4.9, 0.6, 1.57]} rotation={[1.87, -1.2, 1.19]} scale={2.03}>
                  <T.Mesh
                    name="polySurface076_lambert12_0"
                    geometry={gltf.nodes.polySurface076_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface077"
                  position={[-3.56, 0.93, 4.96]}
                  rotation={[-1.31, -0.46, 2.12]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface077_lambert12_0"
                    geometry={gltf.nodes.polySurface077_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface078"
                  position={[-5.13, -0.16, 3.54]}
                  rotation={[-1.35, -0.48, 2.01]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface078_lambert12_0"
                    geometry={gltf.nodes.polySurface078_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface079" position={[-3.65, 0.15, 5.6]} rotation={[1.31, -1.2, 0.59]} scale={2.03}>
                  <T.Mesh
                    name="polySurface079_lambert12_0"
                    geometry={gltf.nodes.polySurface079_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface080"
                  position={[-5.35, 0.78, 3.72]}
                  rotation={[-0.04, -0.4, 0.35]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface080_lambert12_0"
                    geometry={gltf.nodes.polySurface080_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface081"
                  position={[-1.83, 9.97, 0.41]}
                  rotation={[-2.88, -0.05, 1.93]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface081_lambert12_0"
                    geometry={gltf.nodes.polySurface081_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface082"
                  position={[6.89, 19.6, 0.37]}
                  rotation={[0.01, -0.15, 0.03]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface082_lambert12_0"
                    geometry={gltf.nodes.polySurface082_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface083"
                  position={[-3.46, 0.61, 4.02]}
                  rotation={[-2.31, -0.41, 1.55]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface083_lambert12_0"
                    geometry={gltf.nodes.polySurface083_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface084"
                  position={[0.56, 15.34, 3.57]}
                  rotation={[2.24, -0.21, -2.42]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface084_lambert12_0"
                    geometry={gltf.nodes.polySurface084_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface085"
                  position={[1.59, 16.17, 1.75]}
                  rotation={[-1.99, -0.08, -2.66]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface085_lambert12_0"
                    geometry={gltf.nodes.polySurface085_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface086"
                  position={[-2.16, 12.49, 2.4]}
                  rotation={[-3.05, 0.53, -1.14]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface086_lambert12_0"
                    geometry={gltf.nodes.polySurface086_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface087"
                  position={[-5.59, 0.17, 1.71]}
                  rotation={[-1.5, -0.52, 1.71]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface087_lambert12_0"
                    geometry={gltf.nodes.polySurface087_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface088"
                  position={[1.98, 15.86, 2.33]}
                  rotation={[-3.01, -0.46, -1.66]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface088_lambert12_0"
                    geometry={gltf.nodes.polySurface088_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface089"
                  position={[-0.37, 3.12, 3.53]}
                  rotation={[-2.57, 0.29, -2.31]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface089_lambert12_0"
                    geometry={gltf.nodes.polySurface089_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface090" position={[7.19, 19.6, -0.33]} scale={2.03}>
                  <T.Mesh
                    name="polySurface090_lambert12_0"
                    geometry={gltf.nodes.polySurface090_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface091" position={[7, 19.7, -1.26]} rotation={[-0.01, -0.21, 0]} scale={2.03}>
                  <T.Mesh
                    name="polySurface091_lambert12_0"
                    geometry={gltf.nodes.polySurface091_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface092"
                  position={[-3.27, 1.57, 3.94]}
                  rotation={[-2.32, -0.41, 1.55]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface092_lambert12_0"
                    geometry={gltf.nodes.polySurface092_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface093"
                  position={[-2.45, 10.1, 0.99]}
                  rotation={[-3.04, -0.71, 2.22]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface093_lambert12_0"
                    geometry={gltf.nodes.polySurface093_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface094"
                  position={[-5.97, 0.58, 0.88]}
                  rotation={[1.52, 0.06, 3.13]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface094_lambert12_0"
                    geometry={gltf.nodes.polySurface094_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface095"
                  position={[-5.67, 0.47, 3.62]}
                  rotation={[-1.38, -0.49, 1.95]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface095_lambert12_0"
                    geometry={gltf.nodes.polySurface095_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface096"
                  position={[2.62, 18.81, -0.22]}
                  rotation={[1.74, 0.5, -1.63]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface096_lambert12_0"
                    geometry={gltf.nodes.polySurface096_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface097"
                  position={[-1.88, 13.78, 0.69]}
                  rotation={[-3.13, 0.68, -0.62]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface097_lambert12_0"
                    geometry={gltf.nodes.polySurface097_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface098"
                  position={[-2.95, 3.1, 4.72]}
                  rotation={[-1.2, -0.67, 2.13]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface098_lambert12_0"
                    geometry={gltf.nodes.polySurface098_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface099"
                  position={[-1.56, 11.75, 2.26]}
                  rotation={[2.78, -0.49, -0.17]}
                  scale={2.03}
                >
                  <T.Mesh
                    name="polySurface099_lambert12_0"
                    geometry={gltf.nodes.polySurface099_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface012" position={[3.97, 9.05, 2.59]} rotation={[0.02, -0.01, 0.02]}>
                  <T.Mesh
                    name="polySurface012_lambert11_0"
                    geometry={gltf.nodes.polySurface012_lambert11_0.geometry}
                    material={gltf.materials.lambert11}
                  />
                </T.Group>
                <T.Group name="polySurface016" position={[3.73, 8.97, 2.05]} scale={[0.45, 0.38, 0.45]}>
                  <T.Mesh
                    name="polySurface016_lambert11_0"
                    geometry={gltf.nodes.polySurface016_lambert11_0.geometry}
                    material={gltf.materials.lambert11}
                  />
                </T.Group>
                <T.Group name="polySurface019" position={[0, 14.8, -47.57]} rotation={[Math.PI / 2, 0, 0]} scale={13}>
                  <T.Mesh
                    name="polySurface019_lambert12_0"
                    geometry={gltf.nodes.polySurface019_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group name="polySurface020" scale={190.02}>
                  <T.Mesh
                    name="polySurface020_lambert12_0"
                    geometry={gltf.nodes.polySurface020_lambert12_0.geometry}
                    material={gltf.materials.lambert12}
                  />
                </T.Group>
                <T.Group
                  name="polySurface028"
                  position={[-7.19, 3.99, -2.39]}
                  rotation={[-1.47, 0.11, -2.46]}
                  scale={[2.09, 1.5, 1.4]}
                >
                  <T.Mesh
                    name="polySurface028_lambert10_0"
                    geometry={gltf.nodes.polySurface028_lambert10_0.geometry}
                    material={gltf.materials.lambert10}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="polySurface01" position={[-0.4, 10.22, -3.77]} rotation={[0.03, 0.49, 0.09]} scale={1.65}>
                <T.Mesh
                  name="polySurface01_lambert10_0"
                  geometry={gltf.nodes.polySurface01_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface010" position={[-0.81, 9.9, 9]}>
                <T.Mesh
                  name="polySurface010_lambert10_0"
                  geometry={gltf.nodes.polySurface010_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0109">
                <T.Mesh
                  name="polySurface0109_lambert11_0"
                  geometry={gltf.nodes.polySurface0109_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface011" position={[0, 0.45, 0]}>
                <T.Mesh
                  name="polySurface011_lambert11_0"
                  geometry={gltf.nodes.polySurface011_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface0110" position={[-0.23, 0, 6.33]} rotation={[0, -0.45, 0]}>
                <T.Mesh
                  name="polySurface0110_lambert10_0"
                  geometry={gltf.nodes.polySurface0110_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0111">
                <T.Mesh
                  name="polySurface0111_lambert10_0"
                  geometry={gltf.nodes.polySurface0111_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0112">
                <T.Mesh
                  name="polySurface0112_lambert12_0"
                  geometry={gltf.nodes.polySurface0112_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface0113" position={[0.61, 0, 2.3]} rotation={[0, -0.16, 0]}>
                <T.Mesh
                  name="polySurface0113_lambert12_0"
                  geometry={gltf.nodes.polySurface0113_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface0114" position={[0.43, 0, 2.79]} rotation={[0, -0.2, 0]}>
                <T.Mesh
                  name="polySurface0114_lambert10_0"
                  geometry={gltf.nodes.polySurface0114_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0115">
                <T.Mesh
                  name="polySurface0115_lambert10_0"
                  geometry={gltf.nodes.polySurface0115_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0116" />
              <T.Group name="polySurface0117">
                <T.Mesh
                  name="polySurface0117_lambert12_0"
                  geometry={gltf.nodes.polySurface0117_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface0118" position={[0.34, 0, 3.44]} rotation={[0, -0.27, 0]}>
                <T.Mesh
                  name="polySurface0118_lambert10_0"
                  geometry={gltf.nodes.polySurface0118_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0119">
                <T.Mesh
                  name="polySurface0119_lambert11_0"
                  geometry={gltf.nodes.polySurface0119_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface0120" position={[0, 0.6, 0]} />
              <T.Group
                name="polySurface0121"
                position={[-19.29, -0.77, 8.45]}
                rotation={[Math.PI, -1.05, Math.PI]}
                scale={1.16}
              />
              <T.Group name="polySurface0122" position={[0.86, -0.36, 1.97]} rotation={[-0.44, 0, -0.08]} />
              <T.Group name="polySurface0123" position={[2.32, 2.19, -1.98]} rotation={[-0.23, 0.54, 0.23]} />
              <T.Group name="polySurface0126" position={[5.32, -1.58, 8]} rotation={[0, -1.41, 0]} scale={1.45} />
              <T.Group
                name="polySurface0127"
                position={[-44.43, 15.36, 17]}
                rotation={[-Math.PI / 2, 0, 1.94]}
                scale={[-12.82, -13, -13]}
              >
                <T.Mesh
                  name="polySurface0127_lambert12_0"
                  geometry={gltf.nodes.polySurface0127_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface0129">
                <T.Mesh
                  name="polySurface0129_lambert10_0"
                  geometry={gltf.nodes.polySurface0129_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface0130" position={[0, 0.08, -0.02]} scale={1.04}>
                <T.Mesh
                  name="polySurface0130_lambert10_0"
                  geometry={gltf.nodes.polySurface0130_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface0131"
                position={[3.24, 15.36, 47.46]}
                rotation={[Math.PI / 2, 0, 3.07]}
                scale={13}
              >
                <T.Mesh
                  name="polySurface0131_lambert12_0"
                  geometry={gltf.nodes.polySurface0131_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group
                name="polySurface0132"
                position={[37.12, 22.64, 50.39]}
                rotation={[1.45, 0.06, 2.66]}
                scale={8.19}
              >
                <T.Mesh
                  name="polySurface0132_lambert12_0"
                  geometry={gltf.nodes.polySurface0132_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface0133">
                <T.Mesh
                  name="polySurface0133_lambert11_0"
                  geometry={gltf.nodes.polySurface0133_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface0134">
                <T.Mesh
                  name="polySurface0134_lambert12_0"
                  geometry={gltf.nodes.polySurface0134_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface014" position={[-3.16, 3.39, -3.32]} scale={[0.4, 0.34, 0.4]}>
                <T.Mesh
                  name="polySurface014_lambert11_0"
                  geometry={gltf.nodes.polySurface014_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group name="polySurface015" position={[1.12, 4.14, 6.13]} scale={[0.29, 0.24, 0.29]}>
                <T.Mesh
                  name="polySurface015_lambert11_0"
                  geometry={gltf.nodes.polySurface015_lambert11_0.geometry}
                  material={gltf.materials.lambert11}
                />
              </T.Group>
              <T.Group
                name="polySurface017"
                position={[-9.4, 6.04, 1.45]}
                rotation={[-0.12, 0.06, 0.02]}
                scale={1.09}
              />
              <T.Group name="polySurface02" position={[-5.11, 5.53, -3.19]}>
                <T.Mesh
                  name="polySurface02_lambert10_0"
                  geometry={gltf.nodes.polySurface02_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface021"
                position={[-39.62, 22.64, 48.45]}
                rotation={[1.48, -0.1, -2.31]}
                scale={8.19}
              >
                <T.Mesh
                  name="polySurface021_lambert12_0"
                  geometry={gltf.nodes.polySurface021_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group name="polySurface023" position={[-8.41, 3.38, 10.43]} rotation={[-0.16, 0.35, 0.08]}>
                <T.Mesh
                  name="polySurface023_lambert10_0"
                  geometry={gltf.nodes.polySurface023_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface025"
                position={[-0.37, 4.39, 8.96]}
                rotation={[-0.21, -0.26, 0.52]}
                scale={0.67}
              >
                <T.Mesh
                  name="polySurface025_lambert10_0"
                  geometry={gltf.nodes.polySurface025_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface026" position={[-3.6, 3.52, -2.57]} rotation={[0.2, -0.09, -0.01]} scale={0.67}>
                <T.Mesh
                  name="polySurface026_lambert10_0"
                  geometry={gltf.nodes.polySurface026_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface027"
                position={[2.16, 4.57, 6.78]}
                rotation={[-1.63, -0.17, 1.43]}
                scale={[1.4, 1, 0.94]}
              >
                <T.Mesh
                  name="polySurface027_lambert10_0"
                  geometry={gltf.nodes.polySurface027_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface029"
                position={[-7.5, 3.61, -2.32]}
                rotation={[-1.69, 0.06, 2.96]}
                scale={[1.4, 1, 0.94]}
              >
                <T.Mesh
                  name="polySurface029_lambert10_0"
                  geometry={gltf.nodes.polySurface029_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface03" position={[-7.11, 3.26, 9.65]} rotation={[-0.05, -0.2, -0.05]} scale={0.67}>
                <T.Mesh
                  name="polySurface03_lambert10_0"
                  geometry={gltf.nodes.polySurface03_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface030"
                position={[-5.37, 3.85, -3.69]}
                rotation={[-1.54, 0.13, 2.18]}
                scale={[2.09, 1.5, 1.4]}
              >
                <T.Mesh
                  name="polySurface030_lambert10_0"
                  geometry={gltf.nodes.polySurface030_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface032" position={[-4.38, 8.32, -2.04]}>
                <T.Mesh
                  name="polySurface032_lambert12_0"
                  geometry={gltf.nodes.polySurface032_lambert12_0.geometry}
                  material={gltf.materials.lambert12}
                />
              </T.Group>
              <T.Group
                name="polySurface033"
                position={[-5.53, 3.1, 8.36]}
                rotation={[-0.21, -0.29, -0.17]}
                scale={0.38}
              >
                <T.Mesh
                  name="polySurface033_lambert10_0"
                  geometry={gltf.nodes.polySurface033_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface034"
                position={[-6.03, 3.16, 8.21]}
                rotation={[-0.24, -0.21, 0.42]}
                scale={0.62}
              >
                <T.Mesh
                  name="polySurface034_lambert10_0"
                  geometry={gltf.nodes.polySurface034_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface035" position={[-5.73, 3.13, 8.61]} rotation={[0.62, -0.9, 0.31]} scale={0.5}>
                <T.Mesh
                  name="polySurface035_lambert10_0"
                  geometry={gltf.nodes.polySurface035_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface036"
                position={[-5.18, 3.52, 11.04]}
                rotation={[-1.63, -0.17, 0.81]}
                scale={[1.4, 1, 0.94]}
              >
                <T.Mesh
                  name="polySurface036_lambert10_0"
                  geometry={gltf.nodes.polySurface036_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface037"
                position={[-5.63, 3.52, 9.29]}
                rotation={[1.55, 0.04, -0.12]}
                scale={[-1.29, -1, -0.94]}
              >
                <T.Mesh
                  name="polySurface037_lambert10_0"
                  geometry={gltf.nodes.polySurface037_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface038"
                position={[-6.76, 3.62, -2.03]}
                rotation={[0.64, 0.86, -0.31]}
                scale={0.97}
              >
                <T.Mesh
                  name="polySurface038_lambert10_0"
                  geometry={gltf.nodes.polySurface038_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface039"
                position={[-10.26, 3.69, 6.66]}
                rotation={[-1.47, -0.03, -1.1]}
                scale={[0.85, 0.61, 0.57]}
              >
                <T.Mesh
                  name="polySurface039_lambert10_0"
                  geometry={gltf.nodes.polySurface039_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface04"
                position={[-5.42, 3.49, 11.21]}
                rotation={[-1.53, -0.12, 0.12]}
                scale={[1.4, 1, 0.94]}
              >
                <T.Mesh
                  name="polySurface04_lambert10_0"
                  geometry={gltf.nodes.polySurface04_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface043" position={[-4.29, 8.58, -2.05]}>
                <T.Mesh
                  name="polySurface043_lambert10_0"
                  geometry={gltf.nodes.polySurface043_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface046">
                <T.Mesh
                  name="polySurface046_lambert10_0"
                  geometry={gltf.nodes.polySurface046_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface047" position={[3.66, 11.7, 0.82]} rotation={[-1, -0.17, 0.81]}>
                <T.Mesh
                  name="polySurface047_lambert10_0"
                  geometry={gltf.nodes.polySurface047_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface049">
                <T.Mesh
                  name="polySurface049_lambert10_0"
                  geometry={gltf.nodes.polySurface049_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group
                name="polySurface05"
                position={[-5.18, 3.52, 11.04]}
                rotation={[-1.63, -0.17, 0.81]}
                scale={[1.4, 1, 0.94]}
              >
                <T.Mesh
                  name="polySurface05_lambert10_0"
                  geometry={gltf.nodes.polySurface05_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface06" position={[2.63, 4.66, 10.33]} rotation={[0.3, 0.36, -0.46]} scale={0.72}>
                <T.Mesh
                  name="polySurface06_lambert10_0"
                  geometry={gltf.nodes.polySurface06_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface07" position={[-2.86, 5.97, 9.5]}>
                <T.Mesh
                  name="polySurface07_lambert10_0"
                  geometry={gltf.nodes.polySurface07_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
              <T.Group name="polySurface09" position={[-0.8, 9.85, 8.78]}>
                <T.Mesh
                  name="polySurface09_lambert10_0"
                  geometry={gltf.nodes.polySurface09_lambert10_0.geometry}
                  material={gltf.materials.lambert10}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Mesh name="Cube" geometry={gltf.nodes.Cube.geometry} material={gltf.materials.Material} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
