<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\bouquet.glb --root /models/ --printwidth 120 --precision 2
Author: naira001 (https://sketchfab.com/naira001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bouquet-a9ee071fef3543a39317ae2368e6f852
Title: Bouquet
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/bouquet.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="3bc33b1b7c164c7e9ff0700a927fdcfafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="petalss" position={[3.27, 57.72, -13.07]} rotation={[0, 0.08, 0]}>
                <T.Group name="petalsss003" position={[13.36, 55.73, 40.54]} rotation={[0.08, 0, 0]}>
                  <T.Mesh
                    name="petalsss003_petal3_0"
                    geometry={gltf.nodes.petalsss003_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
                <T.Group name="petalsss012" position={[-50.5, 19.99, 75.31]} rotation={[0.16, 0, 0]}>
                  <T.Mesh
                    name="petalsss012_petal1_0"
                    geometry={gltf.nodes.petalsss012_petal1_0.geometry}
                    material={gltf.materials.petal1}
                  />
                </T.Group>
                <T.Group name="petalsss002" position={[7.35, 17.67, -49.2]} rotation={[-0.08, 0, 0]}>
                  <T.Mesh
                    name="petalsss002_petal1_0"
                    geometry={gltf.nodes.petalsss002_petal1_0.geometry}
                    material={gltf.materials.petal1}
                  />
                </T.Group>
                <T.Group name="pasted__inside075" position={[-44.09, -4.54, 72.94]} rotation={[-0.07, 0.08, -0.07]}>
                  <T.Mesh
                    name="pasted__inside075_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside075_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss013" position={[23.64, -11.85, -73.92]} rotation={[0.13, -0.18, -0.13]}>
                  <T.Mesh
                    name="petalsss013_petal3_0"
                    geometry={gltf.nodes.petalsss013_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
                <T.Group name="pasted__inside067" position={[7.05, 45.31, -4.93]}>
                  <T.Mesh
                    name="pasted__inside067_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside067_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="pasted__inside069" position={[17.64, 78.9, 55.41]}>
                  <T.Mesh
                    name="pasted__inside069_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside069_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss006" position={[42.29, 71.38, 28.08]}>
                  <T.Mesh
                    name="petalsss006_petal3_0"
                    geometry={gltf.nodes.petalsss006_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
                <T.Group name="pasted__inside076" position={[-44.09, -4.54, -78.93]}>
                  <T.Mesh
                    name="pasted__inside076_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside076_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="pasted__inside073" position={[7.05, -59.6, -4.93]}>
                  <T.Mesh
                    name="pasted__inside073_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside073_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss008" position={[49.47, -70.61, -12.74]}>
                  <T.Mesh
                    name="petalsss008_petal3_0"
                    geometry={gltf.nodes.petalsss008_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
                <T.Group name="pasted__inside072" position={[57.68, -59.04, 45.16]}>
                  <T.Mesh
                    name="pasted__inside072_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside072_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss010" position={[42.29, -33.53, 28.08]}>
                  <T.Mesh
                    name="petalsss010_petal3_0"
                    geometry={gltf.nodes.petalsss010_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
                <T.Group name="pasted__inside077" position={[-4.62, 2.96, -56.82]}>
                  <T.Mesh
                    name="pasted__inside077_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside077_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="pasted__inside078" position={[-85.26, -14.57, 11.32]}>
                  <T.Mesh
                    name="pasted__inside078_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside078_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="group1" position={[-4.03, 0, -23.18]} rotation={[0, 0.48, 0]}>
                <T.Group name="pasted__inside071" position={[-48.59, 19.21, 65.34]} rotation={[0, 0, -0.16]}>
                  <T.Mesh
                    name="pasted__inside071_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside071_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss001">
                  <T.Mesh
                    name="petalsss001_petal1_0"
                    geometry={gltf.nodes.petalsss001_petal1_0.geometry}
                    material={gltf.materials.petal1}
                  />
                </T.Group>
                <T.Group name="pasted__inside068">
                  <T.Mesh
                    name="pasted__inside068_pasted__leaf_0"
                    geometry={gltf.nodes.pasted__inside068_pasted__leaf_0.geometry}
                    material={gltf.materials.pasted__leaf}
                  />
                </T.Group>
                <T.Group name="petalsss007">
                  <T.Mesh
                    name="petalsss007_petal1_0"
                    geometry={gltf.nodes.petalsss007_petal1_0.geometry}
                    material={gltf.materials.petal1}
                  />
                </T.Group>
                <T.Group name="petalsss011">
                  <T.Mesh
                    name="petalsss011_petal3_0"
                    geometry={gltf.nodes.petalsss011_petal3_0.geometry}
                    material={gltf.materials.petal3}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="hearts" position={[18.01, 79.32, -5.88]} rotation={[0, 0.08, 0]}>
                <T.Group name="heart01" position={[-65.33, -2.2, -42.84]} rotation={[-0.07, 0.08, -0.07]}>
                  <T.Mesh
                    name="heart01_heart_0"
                    geometry={gltf.nodes.heart01_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
                <T.Group name="heart03" position={[63.69, -9.67, 27.45]} rotation={[-0.16, 0, 0]}>
                  <T.Mesh
                    name="heart03_heart_0"
                    geometry={gltf.nodes.heart03_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
                <T.Group name="heart05" position={[24.04, 17.16, 5.27]} rotation={[0, 0, 0.16]}>
                  <T.Mesh
                    name="heart05_heart_0"
                    geometry={gltf.nodes.heart05_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
                <T.Group name="heart08" position={[-15.82, -48.68, 49.52]} rotation={[-0.08, 0, 0]}>
                  <T.Mesh
                    name="heart08_heart_0"
                    geometry={gltf.nodes.heart08_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
                <T.Group name="heart02" position={[-37.02, 71.12, 36.95]}>
                  <T.Mesh
                    name="heart02_heart_0"
                    geometry={gltf.nodes.heart02_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
                <T.Group name="heart04" position={[7.08, 39.13, -49.83]}>
                  <T.Mesh
                    name="heart04_heart_0"
                    geometry={gltf.nodes.heart04_heart_0.geometry}
                    material={gltf.materials.heart}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="bq">
                <T.Group name="b1" position={[-53.66, -64.78, -0.53]} rotation={[-Math.PI / 2, -0.23, 0]} scale={2.08}>
                  <T.Group name="petal01">
                    <T.Mesh
                      name="petal01_petal1_0"
                      geometry={gltf.nodes.petal01_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="petal002">
                    <T.Mesh
                      name="petal002_petal2_0"
                      geometry={gltf.nodes.petal002_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal003">
                    <T.Mesh
                      name="pasted__petal003_petal3_0"
                      geometry={gltf.nodes.pasted__petal003_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal004">
                    <T.Mesh
                      name="pasted__petal004_petal2_0"
                      geometry={gltf.nodes.pasted__petal004_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal005">
                    <T.Mesh
                      name="pasted__petal005_petal1_0"
                      geometry={gltf.nodes.pasted__petal005_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal006">
                    <T.Mesh
                      name="pasted__petal006_petal1_0"
                      geometry={gltf.nodes.pasted__petal006_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal007">
                    <T.Mesh
                      name="pasted__petal007_petal2_0"
                      geometry={gltf.nodes.pasted__petal007_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal008">
                    <T.Mesh
                      name="pasted__petal008_petal1_0"
                      geometry={gltf.nodes.pasted__petal008_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside">
                    <T.Mesh
                      name="pasted__inside_petal2_0"
                      geometry={gltf.nodes.pasted__inside_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside002">
                    <T.Mesh
                      name="pasted__inside002_petal2_0"
                      geometry={gltf.nodes.pasted__inside002_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside003">
                    <T.Mesh
                      name="pasted__inside003_petal3_0"
                      geometry={gltf.nodes.pasted__inside003_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside004">
                    <T.Mesh
                      name="pasted__inside004_petal2_0"
                      geometry={gltf.nodes.pasted__inside004_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal009">
                    <T.Mesh
                      name="pasted__petal009_petal2_0"
                      geometry={gltf.nodes.pasted__petal009_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal010">
                    <T.Mesh
                      name="pasted__petal010_petal3_0"
                      geometry={gltf.nodes.pasted__petal010_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal011">
                    <T.Mesh
                      name="pasted__petal011_petal2_0"
                      geometry={gltf.nodes.pasted__petal011_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal012">
                    <T.Mesh
                      name="pasted__petal012_petal2_0"
                      geometry={gltf.nodes.pasted__petal012_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside005">
                    <T.Mesh
                      name="pasted__inside005_petal2_0"
                      geometry={gltf.nodes.pasted__inside005_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__Line002">
                    <T.Mesh
                      name="pasted__Line002_pasted__lower_0"
                      geometry={gltf.nodes.pasted__Line002_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__Line003">
                    <T.Mesh
                      name="pasted__Line003_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line003_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b2" position={[73.28, -219.96, 110.33]} rotation={[-1.48, 0.07, -1.14]} scale={2.54}>
                  <T.Group name="pasted__Line005">
                    <T.Mesh
                      name="pasted__Line005_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line005_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside007">
                    <T.Mesh
                      name="pasted__inside007_petal2_0"
                      geometry={gltf.nodes.pasted__inside007_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside012">
                    <T.Mesh
                      name="pasted__inside012_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside012_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside009">
                    <T.Mesh
                      name="pasted__inside009_petal1_0"
                      geometry={gltf.nodes.pasted__inside009_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal020">
                    <T.Mesh
                      name="pasted__petal020_petal2_0"
                      geometry={gltf.nodes.pasted__petal020_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside011">
                    <T.Mesh
                      name="pasted__inside011_petal2_0"
                      geometry={gltf.nodes.pasted__inside011_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside010">
                    <T.Mesh
                      name="pasted__inside010_petal2_0"
                      geometry={gltf.nodes.pasted__inside010_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside008">
                    <T.Mesh
                      name="pasted__inside008_petal1_0"
                      geometry={gltf.nodes.pasted__inside008_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal013">
                    <T.Mesh
                      name="pasted__petal013_petal1_0"
                      geometry={gltf.nodes.pasted__petal013_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal014">
                    <T.Mesh
                      name="pasted__petal014_petal3_0"
                      geometry={gltf.nodes.pasted__petal014_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal015">
                    <T.Mesh
                      name="pasted__petal015_petal2_0"
                      geometry={gltf.nodes.pasted__petal015_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal016">
                    <T.Mesh
                      name="pasted__petal016_petal1_0"
                      geometry={gltf.nodes.pasted__petal016_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal017">
                    <T.Mesh
                      name="pasted__petal017_petal1_0"
                      geometry={gltf.nodes.pasted__petal017_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal018">
                    <T.Mesh
                      name="pasted__petal018_petal2_0"
                      geometry={gltf.nodes.pasted__petal018_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal019">
                    <T.Mesh
                      name="pasted__petal019_petal1_0"
                      geometry={gltf.nodes.pasted__petal019_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque">
                    <T.Mesh
                      name="pasted__bouque_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal021">
                    <T.Mesh
                      name="pasted__petal021_petal1_0"
                      geometry={gltf.nodes.pasted__petal021_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal022">
                    <T.Mesh
                      name="pasted__petal022_petal2_0"
                      geometry={gltf.nodes.pasted__petal022_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal023">
                    <T.Mesh
                      name="pasted__petal023_petal2_0"
                      geometry={gltf.nodes.pasted__petal023_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal024">
                    <T.Mesh
                      name="pasted__petal024_petal2_0"
                      geometry={gltf.nodes.pasted__petal024_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b003" position={[42.91, -152.08, 272.58]} rotation={[3.11, -0.04, -1.72]} scale={1.85}>
                  <T.Group name="pasted__Line006">
                    <T.Mesh
                      name="pasted__Line006_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line006_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque001">
                    <T.Mesh
                      name="pasted__bouque001_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque001_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside013">
                    <T.Mesh
                      name="pasted__inside013_petal2_0"
                      geometry={gltf.nodes.pasted__inside013_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside014">
                    <T.Mesh
                      name="pasted__inside014_petal2_0"
                      geometry={gltf.nodes.pasted__inside014_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside015">
                    <T.Mesh
                      name="pasted__inside015_petal2_0"
                      geometry={gltf.nodes.pasted__inside015_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside016">
                    <T.Mesh
                      name="pasted__inside016_petal2_0"
                      geometry={gltf.nodes.pasted__inside016_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside017">
                    <T.Mesh
                      name="pasted__inside017_petal2_0"
                      geometry={gltf.nodes.pasted__inside017_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside018">
                    <T.Mesh
                      name="pasted__inside018_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside018_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal025">
                    <T.Mesh
                      name="pasted__petal025_petal2_0"
                      geometry={gltf.nodes.pasted__petal025_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal026">
                    <T.Mesh
                      name="pasted__petal026_petal2_0"
                      geometry={gltf.nodes.pasted__petal026_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal027">
                    <T.Mesh
                      name="pasted__petal027_petal2_0"
                      geometry={gltf.nodes.pasted__petal027_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal028">
                    <T.Mesh
                      name="pasted__petal028_petal1_0"
                      geometry={gltf.nodes.pasted__petal028_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal029">
                    <T.Mesh
                      name="pasted__petal029_petal1_0"
                      geometry={gltf.nodes.pasted__petal029_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal030">
                    <T.Mesh
                      name="pasted__petal030_petal2_0"
                      geometry={gltf.nodes.pasted__petal030_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal031">
                    <T.Mesh
                      name="pasted__petal031_petal2_0"
                      geometry={gltf.nodes.pasted__petal031_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal032">
                    <T.Mesh
                      name="pasted__petal032_petal2_0"
                      geometry={gltf.nodes.pasted__petal032_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal033">
                    <T.Mesh
                      name="pasted__petal033_petal2_0"
                      geometry={gltf.nodes.pasted__petal033_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal034">
                    <T.Mesh
                      name="pasted__petal034_petal2_0"
                      geometry={gltf.nodes.pasted__petal034_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal035">
                    <T.Mesh
                      name="pasted__petal035_petal2_0"
                      geometry={gltf.nodes.pasted__petal035_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal036">
                    <T.Mesh
                      name="pasted__petal036_petal3_0"
                      geometry={gltf.nodes.pasted__petal036_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b004" position={[130.47, -305.15, 20.57]} rotation={[-2.14, 0.59, -1.6]} scale={1.86}>
                  <T.Group name="pasted__Line010">
                    <T.Mesh
                      name="pasted__Line010_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line010_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque003">
                    <T.Mesh
                      name="pasted__bouque003_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque003_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside031">
                    <T.Mesh
                      name="pasted__inside031_petal2_0"
                      geometry={gltf.nodes.pasted__inside031_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside032">
                    <T.Mesh
                      name="pasted__inside032_petal2_0"
                      geometry={gltf.nodes.pasted__inside032_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside033">
                    <T.Mesh
                      name="pasted__inside033_petal2_0"
                      geometry={gltf.nodes.pasted__inside033_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside034">
                    <T.Mesh
                      name="pasted__inside034_petal3_0"
                      geometry={gltf.nodes.pasted__inside034_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside035">
                    <T.Mesh
                      name="pasted__inside035_petal2_0"
                      geometry={gltf.nodes.pasted__inside035_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside036">
                    <T.Mesh
                      name="pasted__inside036_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside036_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal061">
                    <T.Mesh
                      name="pasted__petal061_petal2_0"
                      geometry={gltf.nodes.pasted__petal061_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal062">
                    <T.Mesh
                      name="pasted__petal062_petal1_0"
                      geometry={gltf.nodes.pasted__petal062_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal063">
                    <T.Mesh
                      name="pasted__petal063_petal2_0"
                      geometry={gltf.nodes.pasted__petal063_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal064">
                    <T.Mesh
                      name="pasted__petal064_petal2_0"
                      geometry={gltf.nodes.pasted__petal064_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal065">
                    <T.Mesh
                      name="pasted__petal065_petal1_0"
                      geometry={gltf.nodes.pasted__petal065_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal066">
                    <T.Mesh
                      name="pasted__petal066_petal3_0"
                      geometry={gltf.nodes.pasted__petal066_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal067">
                    <T.Mesh
                      name="pasted__petal067_petal2_0"
                      geometry={gltf.nodes.pasted__petal067_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal068">
                    <T.Mesh
                      name="pasted__petal068_petal2_0"
                      geometry={gltf.nodes.pasted__petal068_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal069">
                    <T.Mesh
                      name="pasted__petal069_petal3_0"
                      geometry={gltf.nodes.pasted__petal069_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal070">
                    <T.Mesh
                      name="pasted__petal070_petal2_0"
                      geometry={gltf.nodes.pasted__petal070_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal071">
                    <T.Mesh
                      name="pasted__petal071_petal2_0"
                      geometry={gltf.nodes.pasted__petal071_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal072">
                    <T.Mesh
                      name="pasted__petal072_petal2_0"
                      geometry={gltf.nodes.pasted__petal072_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b005" position={[199.03, -201.06, 96.13]} rotation={[-1.47, 0.87, -1.41]} scale={1.65}>
                  <T.Group name="pasted__Line007">
                    <T.Mesh
                      name="pasted__Line007_pasted__lower_0"
                      geometry={gltf.nodes.pasted__Line007_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__Line008">
                    <T.Mesh
                      name="pasted__Line008_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line008_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside019">
                    <T.Mesh
                      name="pasted__inside019_petal2_0"
                      geometry={gltf.nodes.pasted__inside019_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside020">
                    <T.Mesh
                      name="pasted__inside020_petal3_0"
                      geometry={gltf.nodes.pasted__inside020_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside021">
                    <T.Mesh
                      name="pasted__inside021_petal2_0"
                      geometry={gltf.nodes.pasted__inside021_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside023">
                    <T.Mesh
                      name="pasted__inside023_petal2_0"
                      geometry={gltf.nodes.pasted__inside023_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside024">
                    <T.Mesh
                      name="pasted__inside024_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside024_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal037">
                    <T.Mesh
                      name="pasted__petal037_petal2_0"
                      geometry={gltf.nodes.pasted__petal037_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal038">
                    <T.Mesh
                      name="pasted__petal038_petal2_0"
                      geometry={gltf.nodes.pasted__petal038_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal040">
                    <T.Mesh
                      name="pasted__petal040_petal2_0"
                      geometry={gltf.nodes.pasted__petal040_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal041">
                    <T.Mesh
                      name="pasted__petal041_petal1_0"
                      geometry={gltf.nodes.pasted__petal041_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal042">
                    <T.Mesh
                      name="pasted__petal042_petal2_0"
                      geometry={gltf.nodes.pasted__petal042_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal043">
                    <T.Mesh
                      name="pasted__petal043_petal3_0"
                      geometry={gltf.nodes.pasted__petal043_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal044">
                    <T.Mesh
                      name="pasted__petal044_petal3_0"
                      geometry={gltf.nodes.pasted__petal044_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal045">
                    <T.Mesh
                      name="pasted__petal045_petal2_0"
                      geometry={gltf.nodes.pasted__petal045_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal046">
                    <T.Mesh
                      name="pasted__petal046_petal3_0"
                      geometry={gltf.nodes.pasted__petal046_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal047">
                    <T.Mesh
                      name="pasted__petal047_petal3_0"
                      geometry={gltf.nodes.pasted__petal047_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal048">
                    <T.Mesh
                      name="pasted__petal048_petal2_0"
                      geometry={gltf.nodes.pasted__petal048_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b006" position={[62.86, -313.06, 156.1]} rotation={[-1.15, 0.4, 2.91]} scale={2.16}>
                  <T.Group name="pasted__Line009">
                    <T.Mesh
                      name="pasted__Line009_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line009_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque002">
                    <T.Mesh
                      name="pasted__bouque002_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque002_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside025">
                    <T.Mesh
                      name="pasted__inside025_petal2_0"
                      geometry={gltf.nodes.pasted__inside025_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside026">
                    <T.Mesh
                      name="pasted__inside026_petal2_0"
                      geometry={gltf.nodes.pasted__inside026_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside027">
                    <T.Mesh
                      name="pasted__inside027_petal2_0"
                      geometry={gltf.nodes.pasted__inside027_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside028">
                    <T.Mesh
                      name="pasted__inside028_petal3_0"
                      geometry={gltf.nodes.pasted__inside028_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside029">
                    <T.Mesh
                      name="pasted__inside029_petal2_0"
                      geometry={gltf.nodes.pasted__inside029_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside030">
                    <T.Mesh
                      name="pasted__inside030_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside030_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal049">
                    <T.Mesh
                      name="pasted__petal049_petal2_0"
                      geometry={gltf.nodes.pasted__petal049_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal050">
                    <T.Mesh
                      name="pasted__petal050_petal2_0"
                      geometry={gltf.nodes.pasted__petal050_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal051">
                    <T.Mesh
                      name="pasted__petal051_petal2_0"
                      geometry={gltf.nodes.pasted__petal051_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal052">
                    <T.Mesh
                      name="pasted__petal052_petal2_0"
                      geometry={gltf.nodes.pasted__petal052_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal053">
                    <T.Mesh
                      name="pasted__petal053_petal3_0"
                      geometry={gltf.nodes.pasted__petal053_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal054">
                    <T.Mesh
                      name="pasted__petal054_petal3_0"
                      geometry={gltf.nodes.pasted__petal054_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal055">
                    <T.Mesh
                      name="pasted__petal055_petal2_0"
                      geometry={gltf.nodes.pasted__petal055_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal056">
                    <T.Mesh
                      name="pasted__petal056_petal2_0"
                      geometry={gltf.nodes.pasted__petal056_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal057">
                    <T.Mesh
                      name="pasted__petal057_petal3_0"
                      geometry={gltf.nodes.pasted__petal057_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal058">
                    <T.Mesh
                      name="pasted__petal058_petal2_0"
                      geometry={gltf.nodes.pasted__petal058_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal059">
                    <T.Mesh
                      name="pasted__petal059_petal2_0"
                      geometry={gltf.nodes.pasted__petal059_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal060">
                    <T.Mesh
                      name="pasted__petal060_petal2_0"
                      geometry={gltf.nodes.pasted__petal060_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group
                  name="b007"
                  position={[-128.58, -237.24, -13.29]}
                  rotation={[-2.27, -0.16, -0.98]}
                  scale={2.34}
                >
                  <T.Group name="pasted__Line014">
                    <T.Mesh
                      name="pasted__Line014_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line014_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque005">
                    <T.Mesh
                      name="pasted__bouque005_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque005_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside049">
                    <T.Mesh
                      name="pasted__inside049_petal2_0"
                      geometry={gltf.nodes.pasted__inside049_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside050">
                    <T.Mesh
                      name="pasted__inside050_petal2_0"
                      geometry={gltf.nodes.pasted__inside050_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside051">
                    <T.Mesh
                      name="pasted__inside051_petal2_0"
                      geometry={gltf.nodes.pasted__inside051_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside052">
                    <T.Mesh
                      name="pasted__inside052_petal2_0"
                      geometry={gltf.nodes.pasted__inside052_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside053">
                    <T.Mesh
                      name="pasted__inside053_petal2_0"
                      geometry={gltf.nodes.pasted__inside053_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside054">
                    <T.Mesh
                      name="pasted__inside054_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside054_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal097">
                    <T.Mesh
                      name="pasted__petal097_petal3_0"
                      geometry={gltf.nodes.pasted__petal097_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal098">
                    <T.Mesh
                      name="pasted__petal098_petal2_0"
                      geometry={gltf.nodes.pasted__petal098_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal099">
                    <T.Mesh
                      name="pasted__petal099_petal2_0"
                      geometry={gltf.nodes.pasted__petal099_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal100">
                    <T.Mesh
                      name="pasted__petal100_petal1_0"
                      geometry={gltf.nodes.pasted__petal100_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal101">
                    <T.Mesh
                      name="pasted__petal101_petal1_0"
                      geometry={gltf.nodes.pasted__petal101_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal102">
                    <T.Mesh
                      name="pasted__petal102_petal3_0"
                      geometry={gltf.nodes.pasted__petal102_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal103">
                    <T.Mesh
                      name="pasted__petal103_petal2_0"
                      geometry={gltf.nodes.pasted__petal103_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal104">
                    <T.Mesh
                      name="pasted__petal104_petal2_0"
                      geometry={gltf.nodes.pasted__petal104_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal105">
                    <T.Mesh
                      name="pasted__petal105_petal3_0"
                      geometry={gltf.nodes.pasted__petal105_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal106">
                    <T.Mesh
                      name="pasted__petal106_petal1_0"
                      geometry={gltf.nodes.pasted__petal106_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal107">
                    <T.Mesh
                      name="pasted__petal107_petal2_0"
                      geometry={gltf.nodes.pasted__petal107_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal108">
                    <T.Mesh
                      name="pasted__petal108_petal2_0"
                      geometry={gltf.nodes.pasted__petal108_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b008" position={[-153.31, -233.6, 134.05]} rotation={[-1.64, -1.09, -1.64]} scale={2}>
                  <T.Group name="pasted__Line011">
                    <T.Mesh
                      name="pasted__Line011_pasted__lower_0"
                      geometry={gltf.nodes.pasted__Line011_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__Line012">
                    <T.Mesh
                      name="pasted__Line012_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line012_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside037">
                    <T.Mesh
                      name="pasted__inside037_petal1_0"
                      geometry={gltf.nodes.pasted__inside037_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside038">
                    <T.Mesh
                      name="pasted__inside038_petal2_0"
                      geometry={gltf.nodes.pasted__inside038_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside039">
                    <T.Mesh
                      name="pasted__inside039_petal2_0"
                      geometry={gltf.nodes.pasted__inside039_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside040">
                    <T.Mesh
                      name="pasted__inside040_petal2_0"
                      geometry={gltf.nodes.pasted__inside040_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside041">
                    <T.Mesh
                      name="pasted__inside041_petal2_0"
                      geometry={gltf.nodes.pasted__inside041_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside042">
                    <T.Mesh
                      name="pasted__inside042_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside042_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal073">
                    <T.Mesh
                      name="pasted__petal073_petal1_0"
                      geometry={gltf.nodes.pasted__petal073_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal074">
                    <T.Mesh
                      name="pasted__petal074_petal1_0"
                      geometry={gltf.nodes.pasted__petal074_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal075">
                    <T.Mesh
                      name="pasted__petal075_petal2_0"
                      geometry={gltf.nodes.pasted__petal075_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal076">
                    <T.Mesh
                      name="pasted__petal076_petal2_0"
                      geometry={gltf.nodes.pasted__petal076_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal077">
                    <T.Mesh
                      name="pasted__petal077_petal2_0"
                      geometry={gltf.nodes.pasted__petal077_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal078">
                    <T.Mesh
                      name="pasted__petal078_petal1_0"
                      geometry={gltf.nodes.pasted__petal078_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal079">
                    <T.Mesh
                      name="pasted__petal079_petal1_0"
                      geometry={gltf.nodes.pasted__petal079_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal080">
                    <T.Mesh
                      name="pasted__petal080_petal2_0"
                      geometry={gltf.nodes.pasted__petal080_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal081">
                    <T.Mesh
                      name="pasted__petal081_petal1_0"
                      geometry={gltf.nodes.pasted__petal081_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal082">
                    <T.Mesh
                      name="pasted__petal082_petal2_0"
                      geometry={gltf.nodes.pasted__petal082_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal083">
                    <T.Mesh
                      name="pasted__petal083_petal2_0"
                      geometry={gltf.nodes.pasted__petal083_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal084">
                    <T.Mesh
                      name="pasted__petal084_petal1_0"
                      geometry={gltf.nodes.pasted__petal084_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b009" position={[-57.16, -153.61, 229.79]} rotation={[-0.47, -0.56, -1.07]} scale={1.83}>
                  <T.Group name="pasted__Line013">
                    <T.Mesh
                      name="pasted__Line013_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line013_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque004">
                    <T.Mesh
                      name="pasted__bouque004_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque004_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside043">
                    <T.Mesh
                      name="pasted__inside043_petal2_0"
                      geometry={gltf.nodes.pasted__inside043_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside044">
                    <T.Mesh
                      name="pasted__inside044_petal2_0"
                      geometry={gltf.nodes.pasted__inside044_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside045">
                    <T.Mesh
                      name="pasted__inside045_petal2_0"
                      geometry={gltf.nodes.pasted__inside045_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside046">
                    <T.Mesh
                      name="pasted__inside046_petal1_0"
                      geometry={gltf.nodes.pasted__inside046_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside047">
                    <T.Mesh
                      name="pasted__inside047_petal2_0"
                      geometry={gltf.nodes.pasted__inside047_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside048">
                    <T.Mesh
                      name="pasted__inside048_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside048_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal085">
                    <T.Mesh
                      name="pasted__petal085_petal1_0"
                      geometry={gltf.nodes.pasted__petal085_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal086">
                    <T.Mesh
                      name="pasted__petal086_petal1_0"
                      geometry={gltf.nodes.pasted__petal086_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal087">
                    <T.Mesh
                      name="pasted__petal087_petal2_0"
                      geometry={gltf.nodes.pasted__petal087_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal088">
                    <T.Mesh
                      name="pasted__petal088_petal2_0"
                      geometry={gltf.nodes.pasted__petal088_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal089">
                    <T.Mesh
                      name="pasted__petal089_petal1_0"
                      geometry={gltf.nodes.pasted__petal089_petal1_0.geometry}
                      material={gltf.materials.petal1}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal090">
                    <T.Mesh
                      name="pasted__petal090_petal2_0"
                      geometry={gltf.nodes.pasted__petal090_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal091">
                    <T.Mesh
                      name="pasted__petal091_petal2_0"
                      geometry={gltf.nodes.pasted__petal091_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal092">
                    <T.Mesh
                      name="pasted__petal092_petal2_0"
                      geometry={gltf.nodes.pasted__petal092_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal093">
                    <T.Mesh
                      name="pasted__petal093_petal3_0"
                      geometry={gltf.nodes.pasted__petal093_petal3_0.geometry}
                      material={gltf.materials.petal3}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal094">
                    <T.Mesh
                      name="pasted__petal094_petal2_0"
                      geometry={gltf.nodes.pasted__petal094_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal095">
                    <T.Mesh
                      name="pasted__petal095_petal2_0"
                      geometry={gltf.nodes.pasted__petal095_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal096">
                    <T.Mesh
                      name="pasted__petal096_petal2_0"
                      geometry={gltf.nodes.pasted__petal096_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b010" position={[-82.26, -319.82, 8.63]} rotation={[-2.08, -0.38, -1.32]} scale={1.54}>
                  <T.Group name="pasted__Line015">
                    <T.Mesh
                      name="pasted__Line015_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line015_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque006">
                    <T.Mesh
                      name="pasted__bouque006_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque006_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside055">
                    <T.Mesh
                      name="pasted__inside055_petal2_0"
                      geometry={gltf.nodes.pasted__inside055_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside056">
                    <T.Mesh
                      name="pasted__inside056_petal2_0"
                      geometry={gltf.nodes.pasted__inside056_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside057">
                    <T.Mesh
                      name="pasted__inside057_petal2_0"
                      geometry={gltf.nodes.pasted__inside057_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside058">
                    <T.Mesh
                      name="pasted__inside058_petal2_0"
                      geometry={gltf.nodes.pasted__inside058_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside059">
                    <T.Mesh
                      name="pasted__inside059_petal2_0"
                      geometry={gltf.nodes.pasted__inside059_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal109">
                    <T.Mesh
                      name="pasted__petal109_petal2_0"
                      geometry={gltf.nodes.pasted__petal109_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal110">
                    <T.Mesh
                      name="pasted__petal110_petal2_0"
                      geometry={gltf.nodes.pasted__petal110_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal111">
                    <T.Mesh
                      name="pasted__petal111_petal2_0"
                      geometry={gltf.nodes.pasted__petal111_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal112">
                    <T.Mesh
                      name="pasted__petal112_petal2_0"
                      geometry={gltf.nodes.pasted__petal112_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal113">
                    <T.Mesh
                      name="pasted__petal113_petal2_0"
                      geometry={gltf.nodes.pasted__petal113_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal114">
                    <T.Mesh
                      name="pasted__petal114_petal2_0"
                      geometry={gltf.nodes.pasted__petal114_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal115">
                    <T.Mesh
                      name="pasted__petal115_petal2_0"
                      geometry={gltf.nodes.pasted__petal115_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal116">
                    <T.Mesh
                      name="pasted__petal116_petal2_0"
                      geometry={gltf.nodes.pasted__petal116_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal117">
                    <T.Mesh
                      name="pasted__petal117_petal2_0"
                      geometry={gltf.nodes.pasted__petal117_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal118">
                    <T.Mesh
                      name="pasted__petal118_petal2_0"
                      geometry={gltf.nodes.pasted__petal118_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal119">
                    <T.Mesh
                      name="pasted__petal119_petal2_0"
                      geometry={gltf.nodes.pasted__petal119_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal120">
                    <T.Mesh
                      name="pasted__petal120_petal2_0"
                      geometry={gltf.nodes.pasted__petal120_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="b011" position={[-13.58, -354.71, 155.33]} rotation={[-1.25, -0.07, -1.39]} scale={1.83}>
                  <T.Group name="pasted__Line016">
                    <T.Mesh
                      name="pasted__Line016_pasted__05_-_Default_0"
                      geometry={gltf.nodes['pasted__Line016_pasted__05_-_Default_0'].geometry}
                      material={gltf.materials['pasted__05_-_Default']}
                    />
                  </T.Group>
                  <T.Group name="pasted__bouque007">
                    <T.Mesh
                      name="pasted__bouque007_pasted__lower_0"
                      geometry={gltf.nodes.pasted__bouque007_pasted__lower_0.geometry}
                      material={gltf.materials.pasted__lower}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside061">
                    <T.Mesh
                      name="pasted__inside061_petal2_0"
                      geometry={gltf.nodes.pasted__inside061_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside062">
                    <T.Mesh
                      name="pasted__inside062_petal2_0"
                      geometry={gltf.nodes.pasted__inside062_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside063">
                    <T.Mesh
                      name="pasted__inside063_petal2_0"
                      geometry={gltf.nodes.pasted__inside063_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside064">
                    <T.Mesh
                      name="pasted__inside064_petal2_0"
                      geometry={gltf.nodes.pasted__inside064_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside065">
                    <T.Mesh
                      name="pasted__inside065_petal2_0"
                      geometry={gltf.nodes.pasted__inside065_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__inside066">
                    <T.Mesh
                      name="pasted__inside066_pasted__leaf_0"
                      geometry={gltf.nodes.pasted__inside066_pasted__leaf_0.geometry}
                      material={gltf.materials.pasted__leaf}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal121">
                    <T.Mesh
                      name="pasted__petal121_petal2_0"
                      geometry={gltf.nodes.pasted__petal121_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal122">
                    <T.Mesh
                      name="pasted__petal122_petal2_0"
                      geometry={gltf.nodes.pasted__petal122_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal123">
                    <T.Mesh
                      name="pasted__petal123_petal2_0"
                      geometry={gltf.nodes.pasted__petal123_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal124">
                    <T.Mesh
                      name="pasted__petal124_petal2_0"
                      geometry={gltf.nodes.pasted__petal124_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal125">
                    <T.Mesh
                      name="pasted__petal125_petal2_0"
                      geometry={gltf.nodes.pasted__petal125_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal126">
                    <T.Mesh
                      name="pasted__petal126_petal2_0"
                      geometry={gltf.nodes.pasted__petal126_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal127">
                    <T.Mesh
                      name="pasted__petal127_petal2_0"
                      geometry={gltf.nodes.pasted__petal127_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal128">
                    <T.Mesh
                      name="pasted__petal128_petal2_0"
                      geometry={gltf.nodes.pasted__petal128_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal129">
                    <T.Mesh
                      name="pasted__petal129_petal2_0"
                      geometry={gltf.nodes.pasted__petal129_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal130">
                    <T.Mesh
                      name="pasted__petal130_petal2_0"
                      geometry={gltf.nodes.pasted__petal130_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal131">
                    <T.Mesh
                      name="pasted__petal131_petal2_0"
                      geometry={gltf.nodes.pasted__petal131_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                  <T.Group name="pasted__petal132">
                    <T.Mesh
                      name="pasted__petal132_petal2_0"
                      geometry={gltf.nodes.pasted__petal132_petal2_0.geometry}
                      material={gltf.materials.petal2}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="bag">
                  <T.Group name="polySurface1">
                    <T.Mesh
                      name="polySurface1_paper_0"
                      geometry={gltf.nodes.polySurface1_paper_0.geometry}
                      material={gltf.materials.paper}
                    />
                  </T.Group>
                  <T.Group name="ribbon2">
                    <T.Mesh
                      name="ribbon2_ribbon1_0"
                      geometry={gltf.nodes.ribbon2_ribbon1_0.geometry}
                      material={gltf.materials.ribbon1}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="ribbon">
                  <T.Mesh
                    name="ribbon_ribbon1_0"
                    geometry={gltf.nodes.ribbon_ribbon1_0.geometry}
                    material={gltf.materials.ribbon1}
                  />
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
