<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\candles_set.glb --root /models/ --printwidth 120 --precision 2
Author: shuvalov.di (https://sketchfab.com/shuvalov.di)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/candles-set-f09212756bc94764a8bcfcd3c7e38f8e
Title: Candles set
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/candles_set.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  $: $actions['Animation']?.play()

  console.log(actions)

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="candle_1_0" position={[0.05, 0.09, 0.01]} rotation={[Math.PI / 2, 0, -0.97]} scale={0.24}>
              <T.Mesh name="Object_4" geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Candle_1} />
            </T.Group>
            <T.Group name="candle_wick_1_1" position={[0.06, 0.17, 0]} rotation={[Math.PI / 2, 0, -0.97]} scale={0.24}>
              <T.Mesh name="Object_6" geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Candle_1} />
            </T.Group>
            <T.Group name="candle_2_2" position={[-0.04, 0.06, -0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.24}>
              <T.Mesh name="Object_8" geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.Candle_2} />
            </T.Group>
            <T.Group name="candle_wick_2_3" position={[-0.04, 0.1, -0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.24}>
              <T.Mesh name="Object_10" geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.Candle_2} />
            </T.Group>
            <T.Group name="candle_3_4" position={[-0.05, 0.04, 0.07]} rotation={[Math.PI / 2, 0, 0.09]} scale={0.24}>
              <T.Mesh name="Object_12" geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.Candle_3} />
            </T.Group>
            <T.Group
              name="candle_wick_3_5"
              position={[-0.06, 0.07, 0.07]}
              rotation={[Math.PI / 2, 0, 0.09]}
              scale={0.24}
            >
              <T.Mesh name="Object_14" geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.Candle_3} />
            </T.Group>
            <T.Group
              name="Flame_3_6"
              position={[-0.06, 0.07, 0.07]}
              rotation={[0, -0.09, 0]}
              scale={[1.01, 1.09, 1.01]}
            >
              <T.Mesh
                name="mesh_6"
                geometry={gltf.nodes.mesh_6.geometry}
                material={gltf.materials.Flame}
                morphTargetDictionary={gltf.nodes.mesh_6.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_6.morphTargetInfluences}
              />
            </T.Group>
            <T.Group name="Flame_2_7" position={[-0.04, 0.1, -0.05]} scale={1.13}>
              <T.Mesh
                name="mesh_7"
                geometry={gltf.nodes.mesh_7.geometry}
                material={gltf.materials.Flame}
                morphTargetDictionary={gltf.nodes.mesh_7.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_7.morphTargetInfluences}
              />
            </T.Group>
            <T.Group name="Flame_1_8" position={[0.06, 0.18, 0]} rotation={[0, 0.97, 0]}>
              <T.Mesh
                name="mesh_8"
                geometry={gltf.nodes.mesh_8.geometry}
                material={gltf.materials.Flame}
                morphTargetDictionary={gltf.nodes.mesh_8.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_8.morphTargetInfluences}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
