<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\cave.glb --root /models/ --printwidth 120 --precision 2
Author: Laurie Annis (https://sketchfab.com/laurieannis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crystal-cave-meditation-free-download-b1af78254afb45b798f259c6d881194e
Title: Crystal Cave Meditation - Free Download
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/cave.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <T.Group name="Root">
          <T.Group name="MushroomTiny" position={[447.31, 17.53, 0]} scale={100}>
            <T.Mesh
              name="MushroomTiny_0"
              geometry={gltf.nodes.MushroomTiny_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomSmall" position={[482.9, -25.82, 0]} scale={100}>
            <T.Mesh
              name="MushroomSmall_0"
              geometry={gltf.nodes.MushroomSmall_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomMedium" position={[-502.64, 109.33, 0]} scale={100}>
            <T.Mesh
              name="MushroomMedium_0"
              geometry={gltf.nodes.MushroomMedium_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomLarge" position={[320.13, 376.6, 0]} rotation={[0, 0, 1.77]} scale={100}>
            <T.Mesh
              name="MushroomLarge_0"
              geometry={gltf.nodes.MushroomLarge_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="GeodeRock" position={[-28.5, 342.77, 0]} scale={100}>
            <T.Mesh name="GeodeRock_0" geometry={gltf.nodes.GeodeRock_0.geometry} material={gltf.materials.Root} />
          </T.Group>
          <T.Group name="GeodeCave" scale={100}>
            <T.Mesh name="GeodeCave_0" geometry={gltf.nodes.GeodeCave_0.geometry} material={gltf.materials.Root} />
          </T.Group>
          <T.Group name="CrystalsSmall" position={[-118.45, -438.86, 0]} scale={100}>
            <T.Mesh
              name="CrystalsSmall_0"
              geometry={gltf.nodes.CrystalsSmall_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="CrystalsMedium" position={[452.52, -89.59, 0]} scale={100}>
            <T.Mesh
              name="CrystalsMedium_0"
              geometry={gltf.nodes.CrystalsMedium_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="CrystalsLarge" position={[-479.86, -16.7, 0]} rotation={[0, 0, -3.07]} scale={100}>
            <T.Mesh
              name="CrystalsLarge_0"
              geometry={gltf.nodes.CrystalsLarge_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="CaveFloor" scale={100}>
            <T.Mesh name="CaveFloor_0" geometry={gltf.nodes.CaveFloor_0.geometry} material={gltf.materials.Root} />
          </T.Group>
          <T.Group name="Fairy_Armature" rotation={[0, -Math.PI / 2, 0]} scale={30}>
            <T is={gltf.nodes.Fairy_Armature_rootJoint} />
            <T.Group name="Fairy" rotation={[0, Math.PI / 2, 0]} scale={3.33} />
            <T.SkinnedMesh
              name="Fairy_0"
              geometry={gltf.nodes.Fairy_0.geometry}
              material={gltf.materials.Fairy_Mat}
              skeleton={gltf.nodes.Fairy_0.skeleton}
            />
          </T.Group>
          <T.Group name="MushroomTiny001" position={[278.31, 338.01, 0]} scale={100}>
            <T.Mesh
              name="MushroomTiny001_0"
              geometry={gltf.nodes.MushroomTiny001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomTiny002" position={[-194.37, -505.57, 0]} scale={122.84}>
            <T.Mesh
              name="MushroomTiny002_0"
              geometry={gltf.nodes.MushroomTiny002_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomSmall001" position={[-437.34, 88.08, 0]} rotation={[0, 0, 0.2]} scale={76.61}>
            <T.Mesh
              name="MushroomSmall001_0"
              geometry={gltf.nodes.MushroomSmall001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomMedium001" position={[483.36, 43.95, 0]} rotation={[0, 0, -2.43]} scale={180.52}>
            <T.Mesh
              name="MushroomMedium001_0"
              geometry={gltf.nodes.MushroomMedium001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomSmall002" position={[-152.65, -499.81, 0]} scale={76.61}>
            <T.Mesh
              name="MushroomSmall002_0"
              geometry={gltf.nodes.MushroomSmall002_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomLarge001" position={[-175.4, -468.9, 0]} scale={132.06}>
            <T.Mesh
              name="MushroomLarge001_0"
              geometry={gltf.nodes.MushroomLarge001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="MushroomMedium002" position={[-449.28, 171.76, 0]} rotation={[0, 0, -2.43]} scale={120.57}>
            <T.Mesh
              name="MushroomMedium002_0"
              geometry={gltf.nodes.MushroomMedium002_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group
            name="Fairy_Armature001"
            position={[215.63, 382.67, 0]}
            rotation={[-Math.PI / 2, -0.04, -Math.PI / 2]}
            scale={30}
          >
            <T is={gltf.nodes.Fairy_Armature001_rootJoint} />
            <T.Group name="Fairy001" rotation={[-1.53, Math.PI / 2, 0]} scale={3.33} />
            <T.SkinnedMesh
              name="Fairy001_0"
              geometry={gltf.nodes.Fairy001_0.geometry}
              material={gltf.materials.Fairy_Mat}
              skeleton={gltf.nodes.Fairy001_0.skeleton}
            />
          </T.Group>
          <T.Group
            name="Fairy_Armature003"
            position={[370.52, 531.49, -9.74]}
            rotation={[Math.PI / 2, -1.17, Math.PI / 2]}
            scale={30}
          >
            <T is={gltf.nodes.Fairy_Armature003_rootJoint} />
            <T.Group name="Fairy003" rotation={[0.41, Math.PI / 2, 0]} scale={3.33} />
            <T.SkinnedMesh
              name="Fairy003_0"
              geometry={gltf.nodes.Fairy003_0.geometry}
              material={gltf.materials.Fairy_Mat}
              skeleton={gltf.nodes.Fairy003_0.skeleton}
            />
          </T.Group>
          <T.Group
            name="Fairy_Armature004"
            position={[-715.23, 274.86, -27.98]}
            rotation={[Math.PI / 2, -1.17, Math.PI / 2]}
            scale={30}
          >
            <T is={gltf.nodes.Fairy_Armature004_rootJoint} />
            <T.Group name="Fairy004" rotation={[0.41, Math.PI / 2, 0]} scale={3.33} />
            <T.SkinnedMesh
              name="Fairy004_0"
              geometry={gltf.nodes.Fairy004_0.geometry}
              material={gltf.materials.Fairy_Mat}
              skeleton={gltf.nodes.Fairy004_0.skeleton}
            />
          </T.Group>
          <T.Group name="CrystalsMedium001" position={[-357.36, 412.79, 0]} rotation={[0, 0, -2.49]} scale={100}>
            <T.Mesh
              name="CrystalsMedium001_0"
              geometry={gltf.nodes.CrystalsMedium001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="CrystalsSmall001" position={[180.71, -12.15, 0]} rotation={[0, 0, -1.95]} scale={100}>
            <T.Mesh
              name="CrystalsSmall001_0"
              geometry={gltf.nodes.CrystalsSmall001_0.geometry}
              material={gltf.materials.Root}
            />
          </T.Group>
          <T.Group name="Point002" position={[16.25, -291.58, 300.79]}>
            <T.Group name="Point002_1" />
          </T.Group>
          <T.Group name="Point" position={[349.25, 163.08, 302.18]}>
            <T.Group name="Point_1" />
          </T.Group>
          <T.Group name="Point001" position={[-296.14, 200.25, 299.4]}>
            <T.Group name="Point001_1" />
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
