<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\chocolate.glb --root /models/ --printwidth 120 --precision 2
Author: sundai (https://sketchfab.com/sundai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chocolate-72a3f9948d444a6db198702801648057
Title: Chocolate
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/chocolate.glb')

//   export let opacity;

//   let modelRef;

//   gltf.then((model) => {
//   modelRef = model;
//   modelRef.materials['palette'].transparent = true;
// });

//  $: if(modelRef) {
//   modelRef.materials['palette'].opacity = opacity;
//  } 
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.palette} position={[-61, -46, 22]} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
