<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\cloud_station.glb --root /models/ --printwidth 120 --precision 2
Author: Alexa Kruckenberg (https://sketchfab.com/AlexaKruckenberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-station-26f81b24d83441ba88c7e80a52adbaaf
Title: Cloud Station
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/cloud_station.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.4}>
        <T.Group name="f2aeabd0fe4a43bda9a61acf7a5a4134fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Object_4">
                <T is={gltf.nodes._rootJoint} />
                <T.Group name="hill_1">
                  <T.Group name="hill_1_GEO" position={[0.23, 0.63, 0.79]} scale={[2.15, 1.94, 1.86]}>
                    <T.Mesh
                      name="hill_1_GEO_hills_MAT_0"
                      geometry={gltf.nodes.hill_1_GEO_hills_MAT_0.geometry}
                      material={gltf.materials.hills_MAT}
                    />
                  </T.Group>
                  <T.Group name="house_1_GEO">
                    <T.Group name="roof_GEO">
                      <T.Mesh
                        name="roof_GEO_hill_1_3_MAT_0"
                        geometry={gltf.nodes.roof_GEO_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="walls_GEO">
                      <T.Mesh
                        name="walls_GEO_hill_1_3_MAT_0"
                        geometry={gltf.nodes.walls_GEO_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="house_2_GEO">
                    <T.Group name="roof_GEO_1">
                      <T.Mesh
                        name="roof_GEO_hill_1_3_MAT_0_1"
                        geometry={gltf.nodes.roof_GEO_hill_1_3_MAT_0_1.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="walls_GEO_1">
                      <T.Mesh
                        name="walls_GEO_hill_1_3_MAT_0_1"
                        geometry={gltf.nodes.walls_GEO_hill_1_3_MAT_0_1.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="house_3_GEO">
                    <T.Group name="roof_GEO_2">
                      <T.Mesh
                        name="roof_GEO_hill_1_3_MAT_0_2"
                        geometry={gltf.nodes.roof_GEO_hill_1_3_MAT_0_2.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="walls_GEO_2">
                      <T.Mesh
                        name="walls_GEO_hill_1_3_MAT_0_2"
                        geometry={gltf.nodes.walls_GEO_hill_1_3_MAT_0_2.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="stairs_GEO">
                    <T.Group name="pCube1">
                      <T.Mesh
                        name="pCube1_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube1_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube2">
                      <T.Mesh
                        name="pCube2_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube2_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube3">
                      <T.Mesh
                        name="pCube3_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube3_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube4">
                      <T.Mesh
                        name="pCube4_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube4_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube5">
                      <T.Mesh
                        name="pCube5_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube5_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube6">
                      <T.Mesh
                        name="pCube6_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube6_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube7">
                      <T.Mesh
                        name="pCube7_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube7_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube8">
                      <T.Mesh
                        name="pCube8_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube8_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="sign">
                    <T.Group name="pCylinder3">
                      <T.Mesh
                        name="pCylinder3_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCylinder3_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube9">
                      <T.Mesh
                        name="pCube9_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube9_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube10">
                      <T.Mesh
                        name="pCube10_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube10_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube11">
                      <T.Mesh
                        name="pCube11_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube11_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube12">
                      <T.Mesh
                        name="pCube12_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube12_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="cloud1">
                    <T.Mesh
                      name="cloud1_hill_1_3_MAT_0"
                      geometry={gltf.nodes.cloud1_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="cloud2">
                    <T.Mesh
                      name="cloud2_hill_1_3_MAT_0"
                      geometry={gltf.nodes.cloud2_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="rocks">
                    <T.Group name="rock1">
                      <T.Mesh
                        name="rock1_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock1_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock2">
                      <T.Mesh
                        name="rock2_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock2_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock3">
                      <T.Mesh
                        name="rock3_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock3_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock4">
                      <T.Mesh
                        name="rock4_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock4_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock5">
                      <T.Mesh
                        name="rock5_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock5_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock6">
                      <T.Mesh
                        name="rock6_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock6_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock7">
                      <T.Mesh
                        name="rock7_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock7_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock8">
                      <T.Mesh
                        name="rock8_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock8_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="rock9">
                      <T.Mesh
                        name="rock9_hill_1_3_MAT_0"
                        geometry={gltf.nodes.rock9_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="hill_2">
                  <T.Group name="sign_1">
                    <T.Group name="pCylinder4">
                      <T.Mesh
                        name="pCylinder4_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCylinder4_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube13">
                      <T.Mesh
                        name="pCube13_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube13_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube14">
                      <T.Mesh
                        name="pCube14_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube14_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube15">
                      <T.Mesh
                        name="pCube15_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube15_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="windmillBase">
                    <T.Group name="axle" position={[3.5, 4.89, -3.48]} rotation={[0, 0, 1.21]}>
                      <T.Group name="arm" position={[0, 0.48, 0.06]}>
                        <T.Group name="sail" position={[-3.5, -5.37, 3.42]}>
                          <T.Mesh
                            name="sail_hill_2_4_MAT_0"
                            geometry={gltf.nodes.sail_hill_2_4_MAT_0.geometry}
                            material={gltf.materials.hill_2_4_MAT}
                          />
                        </T.Group>
                        <T.Mesh
                          name="arm_hill_2_4_MAT_0"
                          geometry={gltf.nodes.arm_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="arm1" position={[0.48, 0, 0.06]}>
                        <T.Group name="sail_1" position={[-3.98, -4.89, 3.42]}>
                          <T.Mesh
                            name="sail_hill_2_4_MAT_0_1"
                            geometry={gltf.nodes.sail_hill_2_4_MAT_0_1.geometry}
                            material={gltf.materials.hill_2_4_MAT}
                          />
                        </T.Group>
                        <T.Mesh
                          name="arm1_hill_2_4_MAT_0"
                          geometry={gltf.nodes.arm1_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="arm2" position={[0, -0.48, 0.06]}>
                        <T.Group name="sail_2" position={[-3.5, -4.41, 3.42]}>
                          <T.Mesh
                            name="sail_hill_2_4_MAT_0_2"
                            geometry={gltf.nodes.sail_hill_2_4_MAT_0_2.geometry}
                            material={gltf.materials.hill_2_4_MAT}
                          />
                        </T.Group>
                        <T.Mesh
                          name="arm2_hill_2_4_MAT_0"
                          geometry={gltf.nodes.arm2_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="arm3" position={[-0.48, 0, 0.06]}>
                        <T.Group name="sail_3" position={[-3.01, -4.89, 3.42]}>
                          <T.Mesh
                            name="sail_hill_2_4_MAT_0_3"
                            geometry={gltf.nodes.sail_hill_2_4_MAT_0_3.geometry}
                            material={gltf.materials.hill_2_4_MAT}
                          />
                        </T.Group>
                        <T.Mesh
                          name="arm3_hill_2_4_MAT_0"
                          geometry={gltf.nodes.arm3_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Mesh
                        name="axle_hill_2_4_MAT_0"
                        geometry={gltf.nodes.axle_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Mesh
                      name="windmillBase_hill_2_4_MAT_0"
                      geometry={gltf.nodes.windmillBase_hill_2_4_MAT_0.geometry}
                      material={gltf.materials.hill_2_4_MAT}
                    />
                  </T.Group>
                  <T.Group name="cloud3">
                    <T.Mesh
                      name="cloud3_hill_2_4_MAT_0"
                      geometry={gltf.nodes.cloud3_hill_2_4_MAT_0.geometry}
                      material={gltf.materials.hill_2_4_MAT}
                    />
                  </T.Group>
                  <T.Group name="hill_2_GEO" position={[2.71, 2.65, -3.49]} scale={[1.74, 1.33, 1.69]}>
                    <T.Mesh
                      name="hill_2_GEO_hills_MAT_0"
                      geometry={gltf.nodes.hill_2_GEO_hills_MAT_0.geometry}
                      material={gltf.materials.hills_MAT}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="hill_3">
                  <T.Group name="bridge">
                    <T.Group name="bridgePlanks">
                      <T.Group name="pCube16">
                        <T.Mesh
                          name="pCube16_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube16_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube17">
                        <T.Mesh
                          name="pCube17_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube17_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube18">
                        <T.Mesh
                          name="pCube18_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube18_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube19">
                        <T.Mesh
                          name="pCube19_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube19_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube20">
                        <T.Mesh
                          name="pCube20_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube20_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube21">
                        <T.Mesh
                          name="pCube21_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube21_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube22">
                        <T.Mesh
                          name="pCube22_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube22_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube23">
                        <T.Mesh
                          name="pCube23_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube23_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube24">
                        <T.Mesh
                          name="pCube24_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube24_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCube25">
                        <T.Mesh
                          name="pCube25_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCube25_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                    </T.Group>
                    <T.Group name="supportRopes">
                      <T.Group name="pCylinder5">
                        <T.Mesh
                          name="pCylinder5_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder5_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder6">
                        <T.Mesh
                          name="pCylinder6_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder6_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder7">
                        <T.Mesh
                          name="pCylinder7_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder7_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder8">
                        <T.Mesh
                          name="pCylinder8_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder8_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder9">
                        <T.Mesh
                          name="pCylinder9_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder9_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder10">
                        <T.Mesh
                          name="pCylinder10_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder10_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder11">
                        <T.Mesh
                          name="pCylinder11_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder11_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder12">
                        <T.Mesh
                          name="pCylinder12_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder12_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder13">
                        <T.Mesh
                          name="pCylinder13_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder13_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder14">
                        <T.Mesh
                          name="pCylinder14_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder14_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder15">
                        <T.Mesh
                          name="pCylinder15_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder15_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder16">
                        <T.Mesh
                          name="pCylinder16_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder16_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder17">
                        <T.Mesh
                          name="pCylinder17_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder17_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder18">
                        <T.Mesh
                          name="pCylinder18_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder18_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder19">
                        <T.Mesh
                          name="pCylinder19_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder19_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder20">
                        <T.Mesh
                          name="pCylinder20_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder20_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder21">
                        <T.Mesh
                          name="pCylinder21_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder21_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder22">
                        <T.Mesh
                          name="pCylinder22_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder22_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder23">
                        <T.Mesh
                          name="pCylinder23_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder23_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="pCylinder24">
                        <T.Mesh
                          name="pCylinder24_hill_2_4_MAT_0"
                          geometry={gltf.nodes.pCylinder24_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                    </T.Group>
                    <T.Group name="ropes">
                      <T.Group name="rope1">
                        <T.Mesh
                          name="rope1_hill_2_4_MAT_0"
                          geometry={gltf.nodes.rope1_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="rope2">
                        <T.Mesh
                          name="rope2_hill_2_4_MAT_0"
                          geometry={gltf.nodes.rope2_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="rope3">
                        <T.Mesh
                          name="rope3_hill_2_4_MAT_0"
                          geometry={gltf.nodes.rope3_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                      <T.Group name="rope4">
                        <T.Mesh
                          name="rope4_hill_2_4_MAT_0"
                          geometry={gltf.nodes.rope4_hill_2_4_MAT_0.geometry}
                          material={gltf.materials.hill_2_4_MAT}
                        />
                      </T.Group>
                    </T.Group>
                  </T.Group>
                  <T.Group name="weatherStation" position={[0, -0.29, 0]}>
                    <T.Group name="polySurface2">
                      <T.Mesh
                        name="polySurface2_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface2_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pTorus1">
                      <T.Mesh
                        name="pTorus1_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pTorus1_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pTorus2">
                      <T.Mesh
                        name="pTorus2_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pTorus2_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pTorus3">
                      <T.Mesh
                        name="pTorus3_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pTorus3_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface3">
                      <T.Mesh
                        name="polySurface3_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface3_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface4">
                      <T.Mesh
                        name="polySurface4_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface4_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface5">
                      <T.Mesh
                        name="polySurface5_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface5_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface6">
                      <T.Mesh
                        name="polySurface6_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface6_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface7">
                      <T.Mesh
                        name="polySurface7_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface7_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface8">
                      <T.Mesh
                        name="polySurface8_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface8_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface9">
                      <T.Mesh
                        name="polySurface9_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface9_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface10">
                      <T.Mesh
                        name="polySurface10_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface10_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface11">
                      <T.Mesh
                        name="polySurface11_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface11_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="polySurface12">
                      <T.Mesh
                        name="polySurface12_hill_1_3_MAT_0"
                        geometry={gltf.nodes.polySurface12_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="windSock">
                    <T.Group name="pCylinder27">
                      <T.Mesh
                        name="pCylinder27_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCylinder27_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCylinder25">
                      <T.Mesh
                        name="pCylinder25_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCylinder25_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCylinder26" />
                    <T.Group name="pCylinder28">
                      <T.Mesh
                        name="pCylinder28_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCylinder28_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="cloud_sign">
                    <T.Group name="pCube26">
                      <T.Mesh
                        name="pCube26_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube26_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube27">
                      <T.Mesh
                        name="pCube27_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube27_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube28">
                      <T.Mesh
                        name="pCube28_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube28_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="cloud">
                      <T.Mesh
                        name="cloud_hill_1_3_MAT_0"
                        geometry={gltf.nodes.cloud_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="sign_2">
                    <T.Group name="pCylinder3_1">
                      <T.Mesh
                        name="pCylinder3_hill_1_3_MAT_0_1"
                        geometry={gltf.nodes.pCylinder3_hill_1_3_MAT_0_1.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube9_1">
                      <T.Mesh
                        name="pCube9_hill_1_3_MAT_0_1"
                        geometry={gltf.nodes.pCube9_hill_1_3_MAT_0_1.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube34">
                      <T.Mesh
                        name="pCube34_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube34_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube35">
                      <T.Mesh
                        name="pCube35_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube35_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube36">
                      <T.Mesh
                        name="pCube36_hill_1_3_MAT_0"
                        geometry={gltf.nodes.pCube36_hill_1_3_MAT_0.geometry}
                        material={gltf.materials.hill_1_3_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="flags1">
                    <T.Mesh
                      name="flags1_hill_1_3_MAT_0"
                      geometry={gltf.nodes.flags1_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="flags2">
                    <T.Mesh
                      name="flags2_hill_1_3_MAT_0"
                      geometry={gltf.nodes.flags2_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="flags3">
                    <T.Mesh
                      name="flags3_hill_1_3_MAT_0"
                      geometry={gltf.nodes.flags3_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="cloud4">
                    <T.Mesh
                      name="cloud4_hill_1_3_MAT_0"
                      geometry={gltf.nodes.cloud4_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="cloud5">
                    <T.Mesh
                      name="cloud5_hill_1_3_MAT_0"
                      geometry={gltf.nodes.cloud5_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="cloud6">
                    <T.Mesh
                      name="cloud6_hill_1_3_MAT_0"
                      geometry={gltf.nodes.cloud6_hill_1_3_MAT_0.geometry}
                      material={gltf.materials.hill_1_3_MAT}
                    />
                  </T.Group>
                  <T.Group name="hill_3_GEO" position={[-3.34, 5.88, -5.6]} scale={[2.53, 1.53, 1.91]}>
                    <T.Mesh
                      name="hill_3_GEO_hills_MAT_0"
                      geometry={gltf.nodes.hill_3_GEO_hills_MAT_0.geometry}
                      material={gltf.materials.hills_MAT}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="hill_4">
                  <T.Group name="sign1" position={[2.84, 5.42, -9.74]} scale={[1.92, 1.47, 1.47]}>
                    <T.Group name="pCylinder3_2">
                      <T.Mesh
                        name="pCylinder3_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCylinder3_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube9_2">
                      <T.Mesh
                        name="pCube9_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube9_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube31">
                      <T.Mesh
                        name="pCube31_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube31_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube32">
                      <T.Mesh
                        name="pCube32_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube32_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube33">
                      <T.Mesh
                        name="pCube33_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube33_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="mansion">
                    <T.Group name="pCube29">
                      <T.Mesh
                        name="pCube29_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube29_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                    <T.Group name="pCube30">
                      <T.Mesh
                        name="pCube30_hill_2_4_MAT_0"
                        geometry={gltf.nodes.pCube30_hill_2_4_MAT_0.geometry}
                        material={gltf.materials.hill_2_4_MAT}
                      />
                    </T.Group>
                  </T.Group>
                  <T.Group name="cloud7">
                    <T.Mesh
                      name="cloud7_hill_2_4_MAT_0"
                      geometry={gltf.nodes.cloud7_hill_2_4_MAT_0.geometry}
                      material={gltf.materials.hill_2_4_MAT}
                    />
                  </T.Group>
                  <T.Group name="hill_4_GEO">
                    <T.Mesh
                      name="hill_4_GEO_hills_MAT_0"
                      geometry={gltf.nodes.hill_4_GEO_hills_MAT_0.geometry}
                      material={gltf.materials.hills_MAT}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="skybox_GEO" position={[0.22, 0.31, -3.78]} scale={15.78}>
                  <T.Mesh
                    name="skybox_GEO_sky_MAT_0"
                    geometry={gltf.nodes.skybox_GEO_sky_MAT_0.geometry}
                    material={gltf.materials.sky_MAT}
                  />
                </T.Group>
                <T.Group name="EVSB_FISHEVSB_FISH">
                  <T.Group name="EVSB_FISHGEO">
                    <T.Group name="EVSB_FISHbody_GEO" />
                    <T.Group name="EVSB_FISHeye_L_GEO">
                      <T.Group name="EVSB_FISHeye_L_GEO_1" />
                      <T.Group name="EVSB_FISHpupil_L_GEO" />
                    </T.Group>
                    <T.Group name="EVSB_FISHeye_R_GEO">
                      <T.Group name="EVSB_FISHeye_R_GEO_1" />
                      <T.Group name="EVSB_FISHpupil_R_GEO" />
                    </T.Group>
                  </T.Group>
                  <T.Group name="EVSB_FISHJOINTS">
                    <T.Group name="Object_291">
                      <T is={gltf.nodes._rootJoint_1} />
                      <T.Group name="Object_295" />
                      <T.Group name="Object_297" />
                      <T.Group name="Object_299" />
                      <T.SkinnedMesh
                        name="Object_293"
                        geometry={gltf.nodes.Object_293.geometry}
                        material={gltf.materials.EVSB_FISHfish_MAT}
                        skeleton={gltf.nodes.Object_293.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_294"
                        geometry={gltf.nodes.Object_294.geometry}
                        material={gltf.materials.EVSB_FISHfish_MAT}
                        skeleton={gltf.nodes.Object_294.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_296"
                        geometry={gltf.nodes.Object_296.geometry}
                        material={gltf.materials.EVSB_FISHfish_MAT}
                        skeleton={gltf.nodes.Object_296.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_298"
                        geometry={gltf.nodes.Object_298.geometry}
                        material={gltf.materials.EVSB_FISHfish_MAT}
                        skeleton={gltf.nodes.Object_298.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_300"
                        geometry={gltf.nodes.Object_300.geometry}
                        material={gltf.materials.EVSB_FISHfish_MAT}
                        skeleton={gltf.nodes.Object_300.skeleton}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="EVSB_FISH1EVSB_FISH">
                  <T.Group name="EVSB_FISH1GEO">
                    <T.Group name="EVSB_FISH1body_GEO" />
                    <T.Group name="EVSB_FISH1eye_L_GEO">
                      <T.Group name="EVSB_FISH1eye_L_GEO_1" />
                      <T.Group name="EVSB_FISH1pupil_L_GEO" />
                    </T.Group>
                    <T.Group name="EVSB_FISH1eye_R_GEO">
                      <T.Group name="EVSB_FISH1eye_R_GEO_1" />
                      <T.Group name="EVSB_FISH1pupil_R_GEO" />
                    </T.Group>
                  </T.Group>
                  <T.Group name="EVSB_FISH1JOINTS">
                    <T.Group name="Object_340">
                      <T is={gltf.nodes._rootJoint_2} />
                      <T.Group name="Object_344" />
                      <T.Group name="Object_346" />
                      <T.Group name="Object_348" />
                      <T.SkinnedMesh
                        name="Object_342"
                        geometry={gltf.nodes.Object_342.geometry}
                        material={gltf.materials.EVSB_FISH1fish_MAT}
                        skeleton={gltf.nodes.Object_342.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_343"
                        geometry={gltf.nodes.Object_343.geometry}
                        material={gltf.materials.EVSB_FISH1fish_MAT}
                        skeleton={gltf.nodes.Object_343.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_345"
                        geometry={gltf.nodes.Object_345.geometry}
                        material={gltf.materials.EVSB_FISH1fish_MAT}
                        skeleton={gltf.nodes.Object_345.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_347"
                        geometry={gltf.nodes.Object_347.geometry}
                        material={gltf.materials.EVSB_FISH1fish_MAT}
                        skeleton={gltf.nodes.Object_347.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_349"
                        geometry={gltf.nodes.Object_349.geometry}
                        material={gltf.materials.EVSB_FISH1fish_MAT}
                        skeleton={gltf.nodes.Object_349.skeleton}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="EVSB_FISH2EVSB_FISH">
                  <T.Group name="EVSB_FISH2GEO">
                    <T.Group name="EVSB_FISH2body_GEO" />
                    <T.Group name="EVSB_FISH2eye_L_GEO">
                      <T.Group name="EVSB_FISH2eye_L_GEO_1" />
                      <T.Group name="EVSB_FISH2pupil_L_GEO" />
                    </T.Group>
                    <T.Group name="EVSB_FISH2eye_R_GEO">
                      <T.Group name="EVSB_FISH2eye_R_GEO_1" />
                      <T.Group name="EVSB_FISH2pupil_R_GEO" />
                    </T.Group>
                  </T.Group>
                  <T.Group name="EVSB_FISH2JOINTS">
                    <T.Group name="Object_389">
                      <T is={gltf.nodes._rootJoint_3} />
                      <T.Group name="Object_393" />
                      <T.Group name="Object_395" />
                      <T.Group name="Object_397" />
                      <T.SkinnedMesh
                        name="Object_391"
                        geometry={gltf.nodes.Object_391.geometry}
                        material={gltf.materials.EVSB_FISH2fish_MAT}
                        skeleton={gltf.nodes.Object_391.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_392"
                        geometry={gltf.nodes.Object_392.geometry}
                        material={gltf.materials.EVSB_FISH2fish_MAT}
                        skeleton={gltf.nodes.Object_392.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_394"
                        geometry={gltf.nodes.Object_394.geometry}
                        material={gltf.materials.EVSB_FISH2fish_MAT}
                        skeleton={gltf.nodes.Object_394.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_396"
                        geometry={gltf.nodes.Object_396.geometry}
                        material={gltf.materials.EVSB_FISH2fish_MAT}
                        skeleton={gltf.nodes.Object_396.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_398"
                        geometry={gltf.nodes.Object_398.geometry}
                        material={gltf.materials.EVSB_FISH2fish_MAT}
                        skeleton={gltf.nodes.Object_398.skeleton}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.SkinnedMesh
                  name="Object_6"
                  geometry={gltf.nodes.Object_6.geometry}
                  material={gltf.materials.hill_1_3_MAT}
                  skeleton={gltf.nodes.Object_6.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
