<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\cute_cat_in_cute_banana.glb --root /models/ --printwidth 120 --precision 2
Author: SOBOL (https://sketchfab.com/sbl-cool)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-cat-in-cute-banana-fb3eee24c9fc422ea256b95d5148931f
Title: Cute Cat in Cute Banana
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers, useTask } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/cute_cat_in_cute_banana.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  $: $actions['metarigAction.001']?.play();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="metarig_26" position={[0.23, 3.38, 0]}>
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.Group name="Cube_20" />
                <T.Group name="Cube001_21" />
                <T.Group name="Cube002_22" />
                <T.Group name="Cube003_23" />
                <T.Group name="Sphere_25" />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_7"
                  geometry={gltf.nodes.Object_7.geometry}
                  material={gltf.materials['Material.002']}
                  skeleton={gltf.nodes.Object_7.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_8"
                  geometry={gltf.nodes.Object_8.geometry}
                  material={gltf.materials['Material.006']}
                  skeleton={gltf.nodes.Object_8.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_10"
                  geometry={gltf.nodes.Object_10.geometry}
                  material={gltf.materials['Material.003']}
                  skeleton={gltf.nodes.Object_10.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_11"
                  geometry={gltf.nodes.Object_11.geometry}
                  material={gltf.materials['Material.006']}
                  skeleton={gltf.nodes.Object_11.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_13"
                  geometry={gltf.nodes.Object_13.geometry}
                  material={gltf.materials['Material.005']}
                  skeleton={gltf.nodes.Object_13.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_14"
                  geometry={gltf.nodes.Object_14.geometry}
                  material={gltf.materials['Material.006']}
                  skeleton={gltf.nodes.Object_14.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_16"
                  geometry={gltf.nodes.Object_16.geometry}
                  material={gltf.materials['Material.004']}
                  skeleton={gltf.nodes.Object_16.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_17"
                  geometry={gltf.nodes.Object_17.geometry}
                  material={gltf.materials['Material.006']}
                  skeleton={gltf.nodes.Object_17.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_19"
                  geometry={gltf.nodes.Object_19.geometry}
                  material={gltf.materials['Material.001']}
                  skeleton={gltf.nodes.Object_19.skeleton}
                />
                <T.SkinnedMesh
                castShadow
                receiveShadow
                  name="Object_20"
                  geometry={gltf.nodes.Object_20.geometry}
                  material={gltf.materials['Material.007']}
                  skeleton={gltf.nodes.Object_20.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
