<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\dancerabbit.glb --root /models/ --printwidth 120 --precision 2
Author: antonmoek (https://sketchfab.com/antonmoek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gangnam-style-dancing-rabbit-character-a06d60f0ab144adc982cdc94bf24e368
Title: Gangnam Style Dancing Rabbit Character
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/dancerabbit.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <T.Group name="8e9044c3623e4ad28d51eb7dd01541d1fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Object_4">
                <T is={gltf.nodes._rootJoint} />
                <T.Group name="Object_6" position={[0, 86.38, 14.2]} />
                <T.Group name="Symmetry_1" position={[0, 86.38, 14.2]} />
                <T.SkinnedMesh
                  name="Object_7"
                  geometry={gltf.nodes.Object_7.geometry}
                  material={gltf.materials.rabbit}
                  skeleton={gltf.nodes.Object_7.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
