<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\heart_valentines_day_obj.glb --root /models/ --printwidth 120 --precision 2
Author: cbcap (https://sketchfab.com/cbcap)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-valentines-day-obj-7a911ec546ba4459b59d24975f1a7576
Title: Heart Valentines Day OBJ
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/heart_valentines_day_obj.glb')

  export let opacity;

  let modelRef;

  gltf.then((model) => {
  modelRef = model;
  console.log(model.materials)
  modelRef.materials['Feather_Main_mt'].transparent = true;
  modelRef.materials['HVD_mt'].transparent = true;
  modelRef.materials['Haert_Big_Mt'].transparent = true;
  modelRef.materials['Hearts_mt'].transparent = true;
  modelRef.materials['Nimbus_mt'].transparent = true;
  modelRef.materials['Tape_mt'].transparent = true;
});

 $: if(modelRef) {
  modelRef.materials['Feather_Main_mt'].opacity = opacity;
  modelRef.materials['HVD_mt'].opacity = opacity;
  modelRef.materials['Haert_Big_Mt'].opacity = opacity;
  modelRef.materials['Hearts_mt'].opacity = opacity;
  modelRef.materials['Nimbus_mt'].opacity = opacity;
  modelRef.materials['Tape_mt'].opacity = opacity;
 } 

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.Feather_Main_mt} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials.Feather_Main_mt} />
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Feather_Main_mt} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.Feather_Main_mt} />
      <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.HVD_mt} />
      <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials.HVD_mt} />
      <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.Haert_Big_Mt} />
      <T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.Hearts_mt} />
      <T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.Nimbus_mt} />
      <T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials.Tape_mt} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
