<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\japanese_bridge_garden.glb --root /models/ --printwidth 120 --precision 2
Author: kristenlee (https://sketchfab.com/kristenlee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-bridge-garden-d122e17593eb4012913cde927486d15a
Title: Japanese Bridge Garden
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/japanese_bridge_garden.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group position={[-304.43, 14.26, -342.8]} rotation={[-Math.PI / 2, 0, -2.38]} scale={13.18}>
        <T.Mesh geometry={gltf.nodes.Cylinder001_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder001_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder001_Material003_0.geometry} material={gltf.materials['Material.003']} />
      </T.Group>
      <T.Group position={[-143.76, 344.93, -106.9]} rotation={[-Math.PI / 2, 0, 0]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder002_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder002_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder002_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Group position={[-7.85, 67.68, 2.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[64.75, 4.71, 6.4]}>
        <T.Mesh geometry={gltf.nodes.Cube005_Material003_0.geometry} material={gltf.materials['Material.003']} />
        <T.Mesh geometry={gltf.nodes.Cube005_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cube005_Material007_0.geometry} material={gltf.materials['Material.007']} />
      </T.Group>
      <T.Group position={[116.56, 413.68, -314.78]} rotation={[-1.75, 1.01, 0.03]} scale={29.64}>
        <T.Mesh geometry={gltf.nodes.Icosphere016_Material003_0.geometry} material={gltf.materials['Material.003']} />
        <T.Mesh geometry={gltf.nodes.Icosphere016_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Icosphere016_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[469.43, 421.78, -411.87]} rotation={[-Math.PI / 2, 0, -0.29]} scale={14.11}>
        <T.Mesh geometry={gltf.nodes.Cylinder003_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder003_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder003_Material003_0.geometry} material={gltf.materials['Material.003']} />
      </T.Group>
      <T.Group position={[-468.02, 500.94, 399.73]} rotation={[-Math.PI / 2, 0, -1.55]} scale={17.69}>
        <T.Mesh geometry={gltf.nodes.Cylinder005_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder005_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder005_Material003_0.geometry} material={gltf.materials['Material.003']} />
      </T.Group>
      <T.Group position={[-201.05, 326.72, -414.34]} rotation={[-Math.PI / 2, 0, -3.07]} scale={16.97}>
        <T.Mesh geometry={gltf.nodes.Cylinder006_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder006_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[374.46, 273.07, -454.31]} rotation={[-Math.PI / 2, 0, -3.07]} scale={13.15}>
        <T.Mesh geometry={gltf.nodes.Cylinder007_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder007_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-446.42, 297.56, 249.73]} rotation={[-Math.PI / 2, 0, -2.22]} scale={15.55}>
        <T.Mesh geometry={gltf.nodes.Cylinder004_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder004_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-424, 248.44, 336.47]} rotation={[-Math.PI / 2, 0, 0.36]} scale={11.25}>
        <T.Mesh geometry={gltf.nodes.Cylinder008_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Cylinder008_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[273.91, 90.37, -403.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[19.76, 19.76, 31.62]}>
        <T.Mesh geometry={gltf.nodes.Circle_Material010_0.geometry} material={gltf.materials['Material.010']} />
        <T.Mesh geometry={gltf.nodes.Circle_Material003_0.geometry} material={gltf.materials['Material.003']} />
      </T.Group>
      <T.Group position={[-468.33, 399.07, 551.43]} rotation={[0.05, -0.28, 2.78]} scale={26.67}>
        <T.Mesh geometry={gltf.nodes.Icosphere010_Material003_0.geometry} material={gltf.materials['Material.003']} />
        <T.Mesh geometry={gltf.nodes.Icosphere010_Material010_0.geometry} material={gltf.materials['Material.010']} />
      </T.Group>
      <T.Group position={[-96.28, 373.13, -462.9]} rotation={[-1.13, -0.95, -2.8]} scale={20.32}>
        <T.Mesh geometry={gltf.nodes.Icosphere001_Material003_0.geometry} material={gltf.materials['Material.003']} />
        <T.Mesh geometry={gltf.nodes.Icosphere001_Material001_0.geometry} material={gltf.materials['Material.001']} />
        <T.Mesh geometry={gltf.nodes.Icosphere001_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-13.31, 55.58, 12.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[539.41, 514.64, 17.83]}>
        <T.Mesh geometry={gltf.nodes.Cube_Material016_0.geometry} material={gltf.materials['Material.016']} />
        <T.Mesh geometry={gltf.nodes.Cube_Material008_0.geometry} material={gltf.materials['Material.008']} />
        <T.Mesh geometry={gltf.nodes.Cube_Material009_0.geometry} material={gltf.materials['Material.009']} />
      </T.Group>
      <T.Group position={[163.91, 579.28, -177.12]} rotation={[-Math.PI / 2, 0, 0.89]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder009_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder009_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder009_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Group position={[-203.96, 538.93, 86.05]} rotation={[-Math.PI / 2, 0, 1.18]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder010_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder010_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder010_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Group position={[0.24, 655.78, 42.97]} rotation={[-Math.PI / 2, 0, 1.18]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder011_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder011_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder011_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Group position={[-183.48, 130.39, 151]} rotation={[-Math.PI / 2, 0, 0]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder012_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder012_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder012_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Group position={[-11.39, 130.39, 211.4]} rotation={[-Math.PI / 2, 0, 0]} scale={7.17}>
        <T.Mesh geometry={gltf.nodes.Cylinder013_Material002_0.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh geometry={gltf.nodes.Cylinder013_Material006_0.geometry} material={gltf.materials['Material.006']} />
        <T.Mesh geometry={gltf.nodes.Cylinder013_Material004_0.geometry} material={gltf.materials['Material.004']} />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Plane003_Material005_0.geometry}
        material={gltf.materials['Material.005']}
        position={[0, 106.66, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={565.21}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere018_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[432.38, 108.86, -344.69]}
        rotation={[-Math.PI / 2, 0, -2.98]}
        scale={[45.94, 45.94, 78.14]}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere017_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-400.45, 108.86, -409.79]}
        rotation={[-Math.PI / 2, 0, -2.03]}
        scale={[52.7, 52.7, 89.64]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle001_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-107.32, 107.06, 313.98]}
        rotation={[-Math.PI / 2, 0, 0.6]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle002_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-158.12, 107.06, 272.82]}
        rotation={[-Math.PI / 2, 0, 1.96]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-29.81, 107.06, 340.02]}
        rotation={[-Math.PI / 2, 0, -1.04]}
        scale={25.39}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle004_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-44.27, 107.06, 260.84]}
        rotation={[-Math.PI / 2, 0, 2.95]}
        scale={34.28}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle005_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-111.11, 107.06, 272.82]}
        rotation={[-Math.PI / 2, 0, -2.42]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle006_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-58.15, 107.06, 295.34]}
        rotation={[-Math.PI / 2, 0, -1.69]}
        scale={24.85}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle007_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[79.51, 107.06, -270.8]}
        rotation={[-Math.PI / 2, 0, 2.01]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle008_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-20.47, 107.06, -252.29]}
        rotation={[-Math.PI / 2, 0, -2.91]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle009_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[117.2, 107.06, -317.37]}
        rotation={[-Math.PI / 2, 0, 0.37]}
        scale={25.39}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle010_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[36.74, 107.06, -315.31]}
        rotation={[-Math.PI / 2, 0, -1.92]}
        scale={34.28}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle011_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[38.26, 107.06, -263.99]}
        rotation={[-Math.PI / 2, 0, -1.01]}
        scale={30.61}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle012_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[73.22, 107.06, -327.7]}
        rotation={[-Math.PI / 2, 0, 1.26]}
        scale={24.85}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle013_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[112.81, 107.06, -252.29]}
        rotation={[-Math.PI / 2, 0, -2]}
        scale={25.98}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle014_Material011_0.geometry}
        material={gltf.materials['Material.011']}
        position={[-111.11, 107.06, 139.58]}
        rotation={[-Math.PI / 2, 0, -2.42]}
        scale={39.89}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[-114.29, 107.74, 298.34]}
        rotation={[0.98, -0.29, -2.74]}
        scale={[-2.27, 2.27, 11.46]}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent001_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[-126.33, 108.04, 134.39]}
        rotation={[1.78, 0.63, 1.23]}
        scale={[-2.57, 2.57, 12.99]}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent002_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[-26.58, 107.74, 298.34]}
        rotation={[2.17, 0.28, 0.38]}
        scale={[-2.71, 2.71, 13.72]}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent003_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[41.11, 108.04, -264.51]}
        rotation={[2.04, 0.48, 0.74]}
        scale={[-3.28, 3.28, 16.59]}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent004_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[96.46, 108.04, -308.51]}
        rotation={[2.21, -0.13, -0.17]}
        scale={[-2.35, 2.35, 11.88]}
      />
      <T.Mesh
        geometry={gltf.nodes.Succulent005_Material012_0.geometry}
        material={gltf.materials['Material.012']}
        position={[110.2, 108.04, -260.36]}
        rotation={[2.04, -0.47, -0.73]}
        scale={[-1.87, 1.87, 9.44]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane001_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[374.43, 113.25, 7.07]}
        rotation={[-Math.PI / 2, 0, -1.76]}
        scale={37.53}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane002_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[407.17, 113.25, -57.16]}
        rotation={[-Math.PI / 2, 0, -0.25]}
        scale={32.65}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane004_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[437.14, 113.25, -5.06]}
        rotation={[-Math.PI / 2, 0, 3]}
        scale={29.77}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane005_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[417.59, 113.25, 29.9]}
        rotation={[-Math.PI / 2, 0, -2.05]}
        scale={24.47}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane006_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[455.85, 113.25, 29.9]}
        rotation={[-Math.PI / 2, 0, -1.15]}
        scale={21.18}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane007_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[-385.16, 113.25, -28.09]}
        rotation={[-Math.PI / 2, 0, 1.59]}
        scale={37.53}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane008_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[-403.72, 113.25, 41.57]}
        rotation={[-Math.PI / 2, 0, 3.1]}
        scale={32.65}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[-443.94, 113.25, -3.1]}
        rotation={[-Math.PI / 2, 0, 0.07]}
        scale={29.77}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[-432.14, 113.25, -41.38]}
        rotation={[-Math.PI / 2, 0, 1.3]}
        scale={24.47}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane011_Material009_0.geometry}
        material={gltf.materials['Material.009']}
        position={[-469.56, 113.25, -33.37]}
        rotation={[-Math.PI / 2, 0, 2.21]}
        scale={21.18}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[416.72, 93.43, -249.36]}
        rotation={[-1.63, 0.19, -2.82]}
        scale={[0.71, 0.26, 0.46]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube002_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[333.25, 98.69, -285.45]}
        rotation={[-1.42, 0.13, 2.26]}
        scale={[0.71, 0.26, 0.46]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[342.05, 105.48, 125.15]}
        rotation={[-1.49, -0.18, -2.72]}
        scale={[-0.64, 0.39, 0.41]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-367.12, 103.37, -278.32]}
        rotation={[-1.68, 0.17, -2.58]}
        scale={[0.58, 0.22, 0.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-464.72, 98.23, -296.04]}
        rotation={[-1.48, 0.18, 2.69]}
        scale={[0.58, 0.22, 0.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-142.91, 103.37, -278.32]}
        rotation={[-1.51, 0.19, 2.83]}
        scale={[0.48, 0.18, 0.32]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-386.25, 98.55, 277.42]}
        rotation={[-1.76, -0.07, -1.2]}
        scale={[0.65, 0.35, 0.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube011_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-397.88, 102.88, 347.87]}
        rotation={[-1.71, 0.14, -2.38]}
        scale={[0.82, 0.3, 0.39]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube012_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-395.48, 102.88, 434.85]}
        rotation={[-1.51, -0.19, 0.32]}
        scale={[0.6, 0.27, 0.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube013_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[8.26, 100.95, 452.76]}
        rotation={[-1.65, 0.18, -2.72]}
        scale={[0.71, 0.19, 0.3]}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere002_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-278.35, 108.86, 421.27]}
        rotation={[-Math.PI / 2, 0, -0.82]}
        scale={[36.5, 36.5, 62.08]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
