<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\low_poly_isometric_bedroom.glb --root /models/ --printwidth 120 --precision 2
Author: iLoveYourFace (https://sketchfab.com/iLoveYourFace)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-isometric-bedroom-b00d498259b54c7089761ceeeb8d3080
Title: Low Poly Isometric Bedroom
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/low_poly_isometric_bedroom.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Room_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.Cube020_Tissue_0.geometry}
        material={gltf.materials.Tissue}
        position={[-10.16, -10.58, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube142_Tissue_0.geometry}
        material={gltf.materials.Tissue}
        position={[-10.16, -10.58, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube143_Tissue_0.geometry}
        material={gltf.materials.Tissue}
        position={[-10.16, -10.58, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube144_Tissue_0.geometry}
        material={gltf.materials.Tissue}
        position={[-10.16, -10.58, 0]}
      />
    </T.Group>
    <T.Group position={[805.37, -480.88, -1057.25]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Bed_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.Blanket_Gradient_0.geometry}
        material={gltf.materials.Gradient}
        scale={[2.9, 2.37, 0.53]}
      />
      <T.Mesh
        geometry={gltf.nodes.Pillow_Gradient_0.geometry}
        material={gltf.materials.Gradient}
        position={[-1.86, -1.08, 1.21]}
        scale={[0.52, 1.01, 0.19]}
      />
      <T.Mesh
        geometry={gltf.nodes.Pillow001_Gradient_0.geometry}
        material={gltf.materials.Gradient}
        position={[-1.86, 1.04, 1.21]}
        scale={[0.52, 1.01, 0.19]}
      />
    </T.Group>
    <T.Group position={[605.58, -437.62, -726.32]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.BedsideTable001_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle002_CoffeeTableLegs_0.geometry}
        material={gltf.materials.CoffeeTableLegs}
        position={[0.74, 0, -0.1]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.13, 0.02, 0.02]}
      />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle003_CoffeeTableLegs_0.geometry}
        material={gltf.materials.CoffeeTableLegs}
        position={[0.74, 0, 0.5]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.13, 0.02, 0.02]}
      />
    </T.Group>
    <T.Group position={[1345.85, -212.25, -1509.51]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Cupboard_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle004_Sock1_0.geometry}
        material={gltf.materials.Sock1}
        position={[-0.38, -0.92, -0.11]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.26, 0.04, 0.04]}
      />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle005_Sock1_0.geometry}
        material={gltf.materials.Sock1}
        position={[0.4, -0.92, -0.11]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.26, 0.04, 0.04]}
      />
    </T.Group>
    <T.Group position={[591.68, -343.72, -1353.57]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Lamp_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.LampShade_Gradient_0.geometry}
        material={gltf.materials.Gradient}
        position={[0, 0, 0.64]}
        scale={0.35}
      />
    </T.Group>
    <T.Group position={[605.58, -437.62, -1387.84]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.BedsideTable002_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle006_CoffeeTableLegs_0.geometry}
        material={gltf.materials.CoffeeTableLegs}
        position={[0.74, 0, -0.1]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.13, 0.02, 0.02]}
      />
      <T.Mesh
        geometry={gltf.nodes.DrawerHandle007_CoffeeTableLegs_0.geometry}
        material={gltf.materials.CoffeeTableLegs}
        position={[0.74, 0, 0.5]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.13, 0.02, 0.02]}
      />
    </T.Group>
    <T.Group position={[866.5, -72.49, -1555.11]} rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Cube149_Gradient_0.geometry} material={gltf.materials.Gradient} />
      <T.Mesh geometry={gltf.nodes.Cube149_Poster1_0.geometry} material={gltf.materials.Poster1} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Rug_Gradient_0.geometry}
      material={gltf.materials.Gradient}
      position={[1194.77, -499.66, -1057.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube145_Gradient_0.geometry}
      material={gltf.materials.Gradient}
      position={[594.7, -352.84, -753.74]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube147_Gradient_0.geometry}
      material={gltf.materials.Gradient}
      position={[568.55, -337.27, -682.45]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube148_Gradient_0.geometry}
      material={gltf.materials.Gradient}
      position={[648.31, -347.89, -1365.51]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube146_Gradient_0.geometry}
      material={gltf.materials.Gradient}
      position={[568.55, -351.22, -682.45]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
