<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\nobtn.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  export let opacity;

  const gltf = useGltf('/models/nobtn.glb')

  let modelRef;

gltf.then((model) => {
  modelRef = model;
  modelRef.materials['Material.005'].transparent = true;
  modelRef.materials['Material.006'].transparent = true;
});

 $: if(modelRef) {
  modelRef.materials['Material.006'].opacity = opacity;
  modelRef.materials['Material.005'].opacity = opacity;
 } 

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-2.37, 1.38, -1]}>
      <T.Mesh geometry={gltf.nodes.Cube004.geometry} material={gltf.materials['Material.005']} />
      <T.Mesh geometry={gltf.nodes.Cube004_1.geometry} material={gltf.materials['Material.006']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
