<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\party_girl.glb --root /models/ --printwidth 120 --precision 2
Author: rasanarkunaite (https://sketchfab.com/rasanarkunaite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/party-girl-c94b3652c0384aa39e58f31f9549cfee
Title: Party Girl
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/party_girl.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  $: $actions['Take 001']?.play();

  console.log(actions)
  
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="221d88f3e5404d2a95e6b55196b77b25fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Legs" position={[0, -93.08, 5.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="head" position={[0, 217.21, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={9.57} />
              <T.Group name="hair" position={[-0.09, 237.8, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={21.35} />
              <T.Group name="Hat" position={[-0.25, 291.12, -0.08]} rotation={[-1.5, 0, 0]} scale={20.24} />
              <T.Group name="Area" position={[-221.58, 378.04, 0]} rotation={[-0.14, 0.17, 1]} scale={100}>
                <T.Group name="Object_10" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_11" />
                </T.Group>
              </T.Group>
              <T.Group name="Area001" position={[-280.52, 160.38, 232.19]} rotation={[0.99, 0.34, 1.06]} scale={100}>
                <T.Group name="Object_13" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_14" />
                </T.Group>
              </T.Group>
              <T.Group name="Armature_yes" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Group name="Object_16">
                  <T is={gltf.nodes._rootJoint} />
                  <T.Group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <T.Group name="Object_21" position={[0, -93.08, 5.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <T.Group name="Object_25" position={[0, 217.21, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={9.57} />
                  <T.Group
                    name="Object_27"
                    position={[-0.09, 237.8, 0.02]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={21.35}
                  />
                  <T.Group name="Object_29" position={[-0.25, 291.12, -0.08]} rotation={[-1.5, 0, 0]} scale={20.24} />
                  <T.Group name="Object_81" position={[0, 217.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={9.57} />
                  <T.SkinnedMesh
                    name="Object_19"
                    geometry={gltf.nodes.Object_19.geometry}
                    material={gltf.materials['Red.001']}
                    skeleton={gltf.nodes.Object_19.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_20"
                    geometry={gltf.nodes.Object_20.geometry}
                    material={gltf.materials.Pink}
                    skeleton={gltf.nodes.Object_20.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_22"
                    geometry={gltf.nodes.Object_22.geometry}
                    material={gltf.materials.Legs}
                    skeleton={gltf.nodes.Object_22.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_23"
                    geometry={gltf.nodes.Object_23.geometry}
                    material={gltf.materials.boots_1}
                    skeleton={gltf.nodes.Object_23.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_24"
                    geometry={gltf.nodes.Object_24.geometry}
                    material={gltf.materials.boots_2}
                    skeleton={gltf.nodes.Object_24.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_26"
                    geometry={gltf.nodes.Object_26.geometry}
                    material={gltf.materials.Skin}
                    skeleton={gltf.nodes.Object_26.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_28"
                    geometry={gltf.nodes.Object_28.geometry}
                    material={gltf.materials.Hair}
                    skeleton={gltf.nodes.Object_28.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_30"
                    geometry={gltf.nodes.Object_30.geometry}
                    material={gltf.materials.Pink}
                    skeleton={gltf.nodes.Object_30.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_82"
                    geometry={gltf.nodes.Object_82.geometry}
                    material={gltf.materials.Material}
                    skeleton={gltf.nodes.Object_82.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="earings" position={[0, 217.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={9.57} />
              <T.Group name="Area004" position={[82.83, 393.63, 157.94]} rotation={[0.37, -0.98, -0.29]} scale={100}>
                <T.Group name="Object_85" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_86" />
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
