<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\pop_cat.glb --root /models/ --printwidth 120 --precision 2
Author: rukitu (https://sketchfab.com/rukitu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pop-cat-2d1c8b8514684b0a8d1b8203caa01a95
Title: POP CAT
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/pop_cat.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="tail_1" position={[0.48, 7.97, -0.99]} scale={1.21}>
              <T.Mesh
                name="Object_4"
                geometry={gltf.nodes.Object_4.geometry}
                material={gltf.materials['Material.004']}
              />
            </T.Group>
            <T.Group name="cat_6" position={[0.48, 7.72, -0.99]} scale={1.21}>
              <T.Mesh
                name="mesh_1"
                geometry={gltf.nodes.mesh_1.geometry}
                material={gltf.materials['Material.004']}
                morphTargetDictionary={gltf.nodes.mesh_1.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_1.morphTargetInfluences}
              />
            </T.Group>
            <T.Group name="cat001_7" position={[9.64, 7.72, -0.99]} scale={1.21}>
              <T.Mesh
                name="mesh_2"
                geometry={gltf.nodes.mesh_2.geometry}
                material={gltf.materials['Material.004']}
                morphTargetDictionary={gltf.nodes.mesh_2.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_2.morphTargetInfluences}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
