<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\shaylushay.glb --root /models/ --printwidth 120 --precision 2
Author: wilsonghm99 (https://sketchfab.com/wilsonghm99)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shaylushay-b9983d13b4c84114949021a88ff4804e
Title: Shaylushay
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/shaylushay.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="f9058211b0a040e497f6e6b2a01cebc9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Armature" position={[0, 0.27, 0]} scale={99.85}>
                <T.Group name="Object_5">
                  <T is={gltf.nodes._rootJoint} />
                  <T.Group name="Object_68" position={[0, 0.27, 0]} scale={99.85} />
                  <T.Group name="Object_70" position={[0, 0.27, 0]} scale={99.85} />
                  <T.Group name="Object_72" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <T.Group name="Object_75" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <T.SkinnedMesh
                    name="Object_69"
                    geometry={gltf.nodes.Object_69.geometry}
                    material={gltf.materials.Body}
                    skeleton={gltf.nodes.Object_69.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_71"
                    geometry={gltf.nodes.Object_71.geometry}
                    material={gltf.materials.Body}
                    skeleton={gltf.nodes.Object_71.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_73"
                    geometry={gltf.nodes.Object_73.geometry}
                    material={gltf.materials['Material.001']}
                    skeleton={gltf.nodes.Object_73.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_74"
                    geometry={gltf.nodes.Object_74.geometry}
                    material={gltf.materials.Accesorios}
                    skeleton={gltf.nodes.Object_74.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_76"
                    geometry={gltf.nodes.Object_76.geometry}
                    material={gltf.materials['Material.002']}
                    skeleton={gltf.nodes.Object_76.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="PM3D_Cone3D1003" position={[0, 0.27, 0]} scale={99.85} />
              <T.Group name="Sphere001" position={[0, 0.27, 0]} scale={99.85} />
              <T.Group name="Sphere057" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Plane001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
