<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\shift_happens_-_canyon_diorama.glb --root /models/ --printwidth 120 --precision 2
Author: Klonk Games (https://sketchfab.com/klonkgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shift-happens-canyon-diorama-ffd36dfbfda8432d97388988883f6295
Title: Shift Happens - Canyon Diorama
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/shift_happens_-_canyon_diorama.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.06}>
        <T.Group name="6a42d9dbc12c436aab25ce78cb19acbbfbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="particle199" position={[-69.96, 17.54, -28.9]} scale={0}>
                <T.Mesh
                  name="particle199_sand_particle_0"
                  geometry={gltf.nodes.particle199_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle198" position={[-94.91, 19.2, -5.91]} scale={0}>
                <T.Mesh
                  name="particle198_sand_particle_0"
                  geometry={gltf.nodes.particle198_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle197" position={[-97.1, 16.61, -15.48]} scale={0}>
                <T.Mesh
                  name="particle197_sand_particle_0"
                  geometry={gltf.nodes.particle197_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle196" position={[-85.6, 19.96, -3.04]} scale={0}>
                <T.Mesh
                  name="particle196_sand_particle_0"
                  geometry={gltf.nodes.particle196_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle195" position={[-68.19, 17.89, -28.04]} scale={0}>
                <T.Mesh
                  name="particle195_sand_particle_0"
                  geometry={gltf.nodes.particle195_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle194" position={[-81.35, 19.55, -12.72]} scale={0}>
                <T.Mesh
                  name="particle194_sand_particle_0"
                  geometry={gltf.nodes.particle194_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle193" position={[-53.59, 16.89, -11.79]} scale={0}>
                <T.Mesh
                  name="particle193_sand_particle_0"
                  geometry={gltf.nodes.particle193_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle192" position={[-57.68, 18.59, 15.19]} scale={0}>
                <T.Mesh
                  name="particle192_sand_particle_0"
                  geometry={gltf.nodes.particle192_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle191" position={[-93.75, 18.55, -23.73]} scale={0}>
                <T.Mesh
                  name="particle191_sand_particle_0"
                  geometry={gltf.nodes.particle191_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle190" position={[-83.26, 16.62, 15.41]} scale={0}>
                <T.Mesh
                  name="particle190_sand_particle_0"
                  geometry={gltf.nodes.particle190_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle189" position={[-53.53, 13.27, -4.96]} scale={0}>
                <T.Mesh
                  name="particle189_sand_particle_0"
                  geometry={gltf.nodes.particle189_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle188" position={[-92.28, 18.75, -10.36]} scale={0}>
                <T.Mesh
                  name="particle188_sand_particle_0"
                  geometry={gltf.nodes.particle188_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle187" position={[-87.16, 19.46, -11.48]} scale={0}>
                <T.Mesh
                  name="particle187_sand_particle_0"
                  geometry={gltf.nodes.particle187_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle186" position={[-55.5, 19.57, -7.14]} scale={0}>
                <T.Mesh
                  name="particle186_sand_particle_0"
                  geometry={gltf.nodes.particle186_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle185" position={[-82.04, 19.85, -11.14]} scale={0}>
                <T.Mesh
                  name="particle185_sand_particle_0"
                  geometry={gltf.nodes.particle185_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle184" position={[-70.13, 17.95, -24.02]} scale={0}>
                <T.Mesh
                  name="particle184_sand_particle_0"
                  geometry={gltf.nodes.particle184_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle183" position={[-95.43, 18.62, -28.34]} scale={0}>
                <T.Mesh
                  name="particle183_sand_particle_0"
                  geometry={gltf.nodes.particle183_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle182" position={[-96.16, 17.73, -22.11]} scale={0}>
                <T.Mesh
                  name="particle182_sand_particle_0"
                  geometry={gltf.nodes.particle182_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle181" position={[-56.74, 17.55, 2.77]} scale={0}>
                <T.Mesh
                  name="particle181_sand_particle_0"
                  geometry={gltf.nodes.particle181_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle180" position={[-74.52, 18.41, 15.45]} rotation={[0.93, 1.18, 0.94]} scale={0.05}>
                <T.Mesh
                  name="particle180_sand_particle_0"
                  geometry={gltf.nodes.particle180_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle179"
                position={[-71.44, 17.38, -28.83]}
                rotation={[-3.09, 1.27, 2.82]}
                scale={0.17}
              >
                <T.Mesh
                  name="particle179_sand_particle_0"
                  geometry={gltf.nodes.particle179_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle178" position={[-67.83, 18.96, 6.06]} rotation={[0.57, 1.02, 3.07]} scale={0.3}>
                <T.Mesh
                  name="particle178_sand_particle_0"
                  geometry={gltf.nodes.particle178_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle177"
                position={[-71.34, 18.18, -21.2]}
                rotation={[0.56, -0.11, -2.92]}
                scale={0.42}
              >
                <T.Mesh
                  name="particle177_sand_particle_0"
                  geometry={gltf.nodes.particle177_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle176"
                position={[-92.27, 19.06, -26.39]}
                rotation={[-1.38, -0.16, 2.65]}
                scale={0.51}
              >
                <T.Mesh
                  name="particle176_sand_particle_0"
                  geometry={gltf.nodes.particle176_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle175" position={[-65.93, 20.69, 8.26]} rotation={[-2.33, 0.55, -0.45]} scale={0.53}>
                <T.Mesh
                  name="particle175_sand_particle_0"
                  geometry={gltf.nodes.particle175_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle174"
                position={[-61.72, 19.33, 10.63]}
                rotation={[2.95, -0.95, -1.16]}
                scale={0.55}
              >
                <T.Mesh
                  name="particle174_sand_particle_0"
                  geometry={gltf.nodes.particle174_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle173" position={[-53.46, 18.64, 11]} rotation={[0.65, 0.23, 0.33]} scale={0.57}>
                <T.Mesh
                  name="particle173_sand_particle_0"
                  geometry={gltf.nodes.particle173_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle172" position={[-74.49, 16.46, 15.93]} rotation={[-1.17, 0.95, -1.4]} scale={0.59}>
                <T.Mesh
                  name="particle172_sand_particle_0"
                  geometry={gltf.nodes.particle172_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle171" position={[-96.06, 18.19, -22.03]} rotation={[0.58, -1.15, 3]} scale={0.61}>
                <T.Mesh
                  name="particle171_sand_particle_0"
                  geometry={gltf.nodes.particle171_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle170"
                position={[-91.02, 18.91, 5.16]}
                rotation={[-1.48, -1.37, -1.66]}
                scale={0.62}
              >
                <T.Mesh
                  name="particle170_sand_particle_0"
                  geometry={gltf.nodes.particle170_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle169" position={[-88.69, 19.94, 2.08]} rotation={[-1.13, -0.01, 0.44]} scale={0.64}>
                <T.Mesh
                  name="particle169_sand_particle_0"
                  geometry={gltf.nodes.particle169_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle168"
                position={[-95.05, 19.39, -24.91]}
                rotation={[-1.31, 0.24, -0.66]}
                scale={0.66}
              >
                <T.Mesh
                  name="particle168_sand_particle_0"
                  geometry={gltf.nodes.particle168_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle167" position={[-97.95, 17.27, -14.93]} rotation={[-1.2, 0.56, 2]} scale={0.68}>
                <T.Mesh
                  name="particle167_sand_particle_0"
                  geometry={gltf.nodes.particle167_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle166" position={[-55.23, 15.83, -20.11]} rotation={[1.21, 0.59, 0.25]} scale={0.7}>
                <T.Mesh
                  name="particle166_sand_particle_0"
                  geometry={gltf.nodes.particle166_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle165"
                position={[-72.8, 17.83, -30.94]}
                rotation={[-2.16, -0.63, 0.64]}
                scale={0.72}
              >
                <T.Mesh
                  name="particle165_sand_particle_0"
                  geometry={gltf.nodes.particle165_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle164" position={[-74.49, 17.8, 4.59]} rotation={[1.5, -0.22, 3]} scale={0.74}>
                <T.Mesh
                  name="particle164_sand_particle_0"
                  geometry={gltf.nodes.particle164_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle163" position={[-69.57, 19.98, 10.19]} rotation={[-3, -0.35, 2.98]} scale={0.76}>
                <T.Mesh
                  name="particle163_sand_particle_0"
                  geometry={gltf.nodes.particle163_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle162" position={[-68.4, 20.98, 12.28]} rotation={[2.72, 0.18, 2.45]} scale={0.78}>
                <T.Mesh
                  name="particle162_sand_particle_0"
                  geometry={gltf.nodes.particle162_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle161" position={[-55.61, 18.13, 0.71]} rotation={[-0.54, 0.17, 0.81]} scale={0.8}>
                <T.Mesh
                  name="particle161_sand_particle_0"
                  geometry={gltf.nodes.particle161_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle160" position={[-76.62, 19.29, -20.62]} rotation={[3.13, 0.85, -0.9]} scale={0.82}>
                <T.Mesh
                  name="particle160_sand_particle_0"
                  geometry={gltf.nodes.particle160_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle159"
                position={[-69.99, 17.31, -18.56]}
                rotation={[-1.95, -1.04, 0.04]}
                scale={0.84}
              >
                <T.Mesh
                  name="particle159_sand_particle_0"
                  geometry={gltf.nodes.particle159_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle158" position={[-78.2, 18.47, 8.36]} rotation={[-0.61, 0.02, 0.51]} scale={0.86}>
                <T.Mesh
                  name="particle158_sand_particle_0"
                  geometry={gltf.nodes.particle158_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle157" position={[-86.47, 18.92, 13.95]} rotation={[1.48, -0.37, 1.63]} scale={0.88}>
                <T.Mesh
                  name="particle157_sand_particle_0"
                  geometry={gltf.nodes.particle157_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle156" position={[-62.32, 19.41, 12.87]} rotation={[-1.11, -0.38, 1.64]} scale={0.9}>
                <T.Mesh
                  name="particle156_sand_particle_0"
                  geometry={gltf.nodes.particle156_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle155" position={[-93.17, 21.1, -7.39]} rotation={[2.94, 0.42, 2.62]} scale={0.92}>
                <T.Mesh
                  name="particle155_sand_particle_0"
                  geometry={gltf.nodes.particle155_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle154"
                position={[-71.89, 18.29, -30.58]}
                rotation={[-0.71, 0.11, 2.69]}
                scale={0.94}
              >
                <T.Mesh
                  name="particle154_sand_particle_0"
                  geometry={gltf.nodes.particle154_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle153"
                position={[-91.86, 19.86, -17.15]}
                rotation={[1.35, 0.08, -0.95]}
                scale={0.96}
              >
                <T.Mesh
                  name="particle153_sand_particle_0"
                  geometry={gltf.nodes.particle153_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle152"
                position={[-93.28, 20.38, -0.24]}
                rotation={[-2.33, 0.96, -0.54]}
                scale={0.98}
              >
                <T.Mesh
                  name="particle152_sand_particle_0"
                  geometry={gltf.nodes.particle152_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle151" position={[-76.86, 19.59, -20.85]} rotation={[-1.63, 0.18, -2.94]}>
                <T.Mesh
                  name="particle151_sand_particle_0"
                  geometry={gltf.nodes.particle151_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle150"
                position={[-94.02, 18.06, -18.65]}
                rotation={[-2.09, -0.54, 3.08]}
                scale={0.97}
              >
                <T.Mesh
                  name="particle150_sand_particle_0"
                  geometry={gltf.nodes.particle150_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle149" position={[-97.8, 18.5, -10.34]} rotation={[2.65, -0.17, -0.1]} scale={0.94}>
                <T.Mesh
                  name="particle149_sand_particle_0"
                  geometry={gltf.nodes.particle149_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle148" position={[-75.12, 19.01, -25.22]} rotation={[1.12, 1.24, 1.07]} scale={0.91}>
                <T.Mesh
                  name="particle148_sand_particle_0"
                  geometry={gltf.nodes.particle148_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle147" position={[-96.8, 20.9, 1.64]} rotation={[2.26, -0.49, -1.72]} scale={0.87}>
                <T.Mesh
                  name="particle147_sand_particle_0"
                  geometry={gltf.nodes.particle147_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle146" position={[-64, 19.53, 15.29]} rotation={[-2.28, -0.91, -1.73]} scale={0.84}>
                <T.Mesh
                  name="particle146_sand_particle_0"
                  geometry={gltf.nodes.particle146_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle145" position={[-66.82, 20.44, 3.58]} rotation={[1.09, 1.26, -1.38]} scale={0.8}>
                <T.Mesh
                  name="particle145_sand_particle_0"
                  geometry={gltf.nodes.particle145_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle144" position={[-82.91, 19.82, -19.82]} rotation={[0.5, 0.61, 1.2]} scale={0.77}>
                <T.Mesh
                  name="particle144_sand_particle_0"
                  geometry={gltf.nodes.particle144_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle143" position={[-81.79, 20.34, 13.01]} rotation={[-1.74, 0.4, 0.32]} scale={0.73}>
                <T.Mesh
                  name="particle143_sand_particle_0"
                  geometry={gltf.nodes.particle143_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle142" position={[-55.66, 19.74, 12.41]} rotation={[0.23, 0.48, 1.4]} scale={0.7}>
                <T.Mesh
                  name="particle142_sand_particle_0"
                  geometry={gltf.nodes.particle142_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle141" position={[-92.08, 20.56, 3.68]} rotation={[-0.08, -0.22, 0.07]} scale={0.67}>
                <T.Mesh
                  name="particle141_sand_particle_0"
                  geometry={gltf.nodes.particle141_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle140" position={[-89.14, 18.74, 12.02]} rotation={[3.13, 0.95, -1.18]} scale={0.63}>
                <T.Mesh
                  name="particle140_sand_particle_0"
                  geometry={gltf.nodes.particle140_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle139" position={[-64.41, 21.85, 7.55]} rotation={[0.01, 0.41, 0.89]} scale={0.6}>
                <T.Mesh
                  name="particle139_sand_particle_0"
                  geometry={gltf.nodes.particle139_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle138" position={[-77.79, 19.09, -24.09]} rotation={[0.98, 0.78, 0.83]} scale={0.56}>
                <T.Mesh
                  name="particle138_sand_particle_0"
                  geometry={gltf.nodes.particle138_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle137"
                position={[-58.22, 19.43, 5.12]}
                rotation={[-2.37, -0.07, -0.48]}
                scale={0.53}
              >
                <T.Mesh
                  name="particle137_sand_particle_0"
                  geometry={gltf.nodes.particle137_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle136"
                position={[-87.05, 21.12, -22.45]}
                rotation={[-1.05, -0.43, 0.5]}
                scale={0.49}
              >
                <T.Mesh
                  name="particle136_sand_particle_0"
                  geometry={gltf.nodes.particle136_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle135" position={[-87.2, 20.86, -25.16]} rotation={[0.82, -0.07, 1.23]} scale={0.46}>
                <T.Mesh
                  name="particle135_sand_particle_0"
                  geometry={gltf.nodes.particle135_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle134"
                position={[-96.52, 21.12, -0.93]}
                rotation={[-1.57, -0.73, 2.16]}
                scale={0.42}
              >
                <T.Mesh
                  name="particle134_sand_particle_0"
                  geometry={gltf.nodes.particle134_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle133" position={[-88.31, 21.51, -0.94]} rotation={[0.59, -0.34, 1.19]} scale={0.39}>
                <T.Mesh
                  name="particle133_sand_particle_0"
                  geometry={gltf.nodes.particle133_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle132" position={[-66.57, 20.39, 0.14]} rotation={[1.98, 1.1, -2.4]} scale={0.36}>
                <T.Mesh
                  name="particle132_sand_particle_0"
                  geometry={gltf.nodes.particle132_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle131" position={[-99.83, 14.62, -6.23]} rotation={[1.66, 0.46, 3.03]} scale={0.32}>
                <T.Mesh
                  name="particle131_sand_particle_0"
                  geometry={gltf.nodes.particle131_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle130"
                position={[-99.82, 16.61, -12.52]}
                rotation={[-0.43, -0.09, -2.58]}
                scale={0.29}
              >
                <T.Mesh
                  name="particle130_sand_particle_0"
                  geometry={gltf.nodes.particle130_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle129" position={[-93.44, 21.47, -0.07]} rotation={[0.76, 0.64, -0.75]} scale={0.25}>
                <T.Mesh
                  name="particle129_sand_particle_0"
                  geometry={gltf.nodes.particle129_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle128" position={[-67.87, 22.1, 6.76]} rotation={[-1.43, -0.82, -1.52]} scale={0.18}>
                <T.Mesh
                  name="particle128_sand_particle_0"
                  geometry={gltf.nodes.particle128_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle127" position={[-74.38, 16.84, -14.88]} rotation={[0.39, 0.73, -1.29]} scale={0.1}>
                <T.Mesh
                  name="particle127_sand_particle_0"
                  geometry={gltf.nodes.particle127_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="particle126"
                position={[-85.28, 20.11, 10.72]}
                rotation={[-2.55, 0.19, -2.66]}
                scale={0.01}
              >
                <T.Mesh
                  name="particle126_sand_particle_0"
                  geometry={gltf.nodes.particle126_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle125" position={[-88.46, 21.89, -1.97]} scale={0}>
                <T.Mesh
                  name="particle125_sand_particle_0"
                  geometry={gltf.nodes.particle125_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle124" position={[-95.74, 20.56, -29.18]} scale={0}>
                <T.Mesh
                  name="particle124_sand_particle_0"
                  geometry={gltf.nodes.particle124_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle123" position={[-86.72, 22.22, -7.17]} scale={0}>
                <T.Mesh
                  name="particle123_sand_particle_0"
                  geometry={gltf.nodes.particle123_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle122" position={[-83.51, 20.83, -16]} scale={0}>
                <T.Mesh
                  name="particle122_sand_particle_0"
                  geometry={gltf.nodes.particle122_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle121" position={[-80.96, 21.21, -15.27]} scale={0}>
                <T.Mesh
                  name="particle121_sand_particle_0"
                  geometry={gltf.nodes.particle121_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle120" position={[-100.18, 14.28, 3.38]} scale={0}>
                <T.Mesh
                  name="particle120_sand_particle_0"
                  geometry={gltf.nodes.particle120_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle119" position={[-64.57, 18.63, -9]} scale={0}>
                <T.Mesh
                  name="particle119_sand_particle_0"
                  geometry={gltf.nodes.particle119_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle118" position={[-95.34, 19.51, -22.43]} scale={0}>
                <T.Mesh
                  name="particle118_sand_particle_0"
                  geometry={gltf.nodes.particle118_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle117" position={[-95.43, 19.83, -12.49]} scale={0}>
                <T.Mesh
                  name="particle117_sand_particle_0"
                  geometry={gltf.nodes.particle117_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle116" position={[-91.77, 21.46, -11.62]} scale={0}>
                <T.Mesh
                  name="particle116_sand_particle_0"
                  geometry={gltf.nodes.particle116_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle115" position={[-61.95, 21.26, -6.36]} scale={0}>
                <T.Mesh
                  name="particle115_sand_particle_0"
                  geometry={gltf.nodes.particle115_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle114" position={[-56.99, 19.33, 1.53]} scale={0}>
                <T.Mesh
                  name="particle114_sand_particle_0"
                  geometry={gltf.nodes.particle114_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle113" position={[-98.31, 20.98, 3.47]} scale={0}>
                <T.Mesh
                  name="particle113_sand_particle_0"
                  geometry={gltf.nodes.particle113_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle112" position={[-91.57, 18.89, -23.46]} scale={0}>
                <T.Mesh
                  name="particle112_sand_particle_0"
                  geometry={gltf.nodes.particle112_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle111" position={[-98.89, 19.1, -21.66]} scale={0}>
                <T.Mesh
                  name="particle111_sand_particle_0"
                  geometry={gltf.nodes.particle111_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle110" position={[-83.8, 20.86, -5.55]} scale={0}>
                <T.Mesh
                  name="particle110_sand_particle_0"
                  geometry={gltf.nodes.particle110_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle109" position={[-78.66, 20.07, 14.42]} scale={0}>
                <T.Mesh
                  name="particle109_sand_particle_0"
                  geometry={gltf.nodes.particle109_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle108" position={[-75.96, 19.84, -16.61]} scale={0}>
                <T.Mesh
                  name="particle108_sand_particle_0"
                  geometry={gltf.nodes.particle108_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle107" position={[-74.16, 20.77, 11.58]} scale={0}>
                <T.Mesh
                  name="particle107_sand_particle_0"
                  geometry={gltf.nodes.particle107_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle106" position={[-76.76, 20.51, -19.22]} scale={0}>
                <T.Mesh
                  name="particle106_sand_particle_0"
                  geometry={gltf.nodes.particle106_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle105" position={[-99.41, 19.61, 6.36]} scale={0}>
                <T.Mesh
                  name="particle105_sand_particle_0"
                  geometry={gltf.nodes.particle105_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle104" position={[-68.93, 20.72, 3.33]} scale={0}>
                <T.Mesh
                  name="particle104_sand_particle_0"
                  geometry={gltf.nodes.particle104_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle103" position={[-73.73, 19.68, 3.11]} scale={0}>
                <T.Mesh
                  name="particle103_sand_particle_0"
                  geometry={gltf.nodes.particle103_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle102" position={[-54.5, 20.26, -7.77]} scale={0}>
                <T.Mesh
                  name="particle102_sand_particle_0"
                  geometry={gltf.nodes.particle102_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle101" position={[-95.28, 19.79, -15.63]} scale={0}>
                <T.Mesh
                  name="particle101_sand_particle_0"
                  geometry={gltf.nodes.particle101_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle100" position={[-92.4, 20.43, -27.26]} scale={0}>
                <T.Mesh
                  name="particle100_sand_particle_0"
                  geometry={gltf.nodes.particle100_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle099" position={[-62.78, 20.68, 10.1]} scale={0}>
                <T.Mesh
                  name="particle099_sand_particle_0"
                  geometry={gltf.nodes.particle099_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle098" position={[-95.54, 18.54, -18.83]} scale={0}>
                <T.Mesh
                  name="particle098_sand_particle_0"
                  geometry={gltf.nodes.particle098_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle097" position={[-88.78, 21.84, -11.01]} scale={0}>
                <T.Mesh
                  name="particle097_sand_particle_0"
                  geometry={gltf.nodes.particle097_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle096" position={[-95.07, 20.22, -24.26]} scale={0}>
                <T.Mesh
                  name="particle096_sand_particle_0"
                  geometry={gltf.nodes.particle096_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle095" position={[-98.31, 20.98, 3.47]} scale={0}>
                <T.Mesh
                  name="particle095_sand_particle_0"
                  geometry={gltf.nodes.particle095_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle094" position={[-69.2, 20.71, 4.79]} scale={0}>
                <T.Mesh
                  name="particle094_sand_particle_0"
                  geometry={gltf.nodes.particle094_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle093" position={[-78.2, 19.42, -24.46]} scale={0}>
                <T.Mesh
                  name="particle093_sand_particle_0"
                  geometry={gltf.nodes.particle093_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle092" position={[-60.09, 20.5, 8.09]} scale={0}>
                <T.Mesh
                  name="particle092_sand_particle_0"
                  geometry={gltf.nodes.particle092_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle091" position={[-79.56, 20.07, -31.16]} scale={0}>
                <T.Mesh
                  name="particle091_sand_particle_0"
                  geometry={gltf.nodes.particle091_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle090" position={[-66.53, 20.67, 1.45]} scale={0}>
                <T.Mesh
                  name="particle090_sand_particle_0"
                  geometry={gltf.nodes.particle090_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle089" position={[-88.44, 20.97, -15.42]} scale={0}>
                <T.Mesh
                  name="particle089_sand_particle_0"
                  geometry={gltf.nodes.particle089_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle088" position={[-67.85, 18.92, -5.2]} scale={0}>
                <T.Mesh
                  name="particle088_sand_particle_0"
                  geometry={gltf.nodes.particle088_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle087" position={[-100.02, 14.22, -8.43]} scale={0}>
                <T.Mesh
                  name="particle087_sand_particle_0"
                  geometry={gltf.nodes.particle087_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle086" position={[-73.65, 18.83, -17.41]} scale={0}>
                <T.Mesh
                  name="particle086_sand_particle_0"
                  geometry={gltf.nodes.particle086_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle085" position={[-80.4, 19.36, -22.89]} scale={0}>
                <T.Mesh
                  name="particle085_sand_particle_0"
                  geometry={gltf.nodes.particle085_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle084" position={[-82.86, 21.7, -10.94]} scale={0}>
                <T.Mesh
                  name="particle084_sand_particle_0"
                  geometry={gltf.nodes.particle084_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle083" position={[-96.22, 21.59, -2.04]} scale={0}>
                <T.Mesh
                  name="particle083_sand_particle_0"
                  geometry={gltf.nodes.particle083_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle082" position={[-82.74, 19.42, -5.14]} scale={0}>
                <T.Mesh
                  name="particle082_sand_particle_0"
                  geometry={gltf.nodes.particle082_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle081" position={[-83.51, 20.12, 9.96]} scale={0}>
                <T.Mesh
                  name="particle081_sand_particle_0"
                  geometry={gltf.nodes.particle081_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle080" position={[-99.25, 19.79, -5.48]} scale={0}>
                <T.Mesh
                  name="particle080_sand_particle_0"
                  geometry={gltf.nodes.particle080_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle079" position={[-82.33, 20.38, -31.02]} scale={0}>
                <T.Mesh
                  name="particle079_sand_particle_0"
                  geometry={gltf.nodes.particle079_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle078" position={[-84.15, 20.37, -16.89]} scale={0}>
                <T.Mesh
                  name="particle078_sand_particle_0"
                  geometry={gltf.nodes.particle078_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle077" position={[-92.11, 20.81, -18.45]} scale={0}>
                <T.Mesh
                  name="particle077_sand_particle_0"
                  geometry={gltf.nodes.particle077_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle076" position={[-75.63, 16.33, -12.9]} scale={0}>
                <T.Mesh
                  name="particle076_sand_particle_0"
                  geometry={gltf.nodes.particle076_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle075" position={[-82.87, 18.52, -3.93]} scale={0}>
                <T.Mesh
                  name="particle075_sand_particle_0"
                  geometry={gltf.nodes.particle075_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle074" position={[-65.44, 19.25, -5.99]} scale={0}>
                <T.Mesh
                  name="particle074_sand_particle_0"
                  geometry={gltf.nodes.particle074_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle073" position={[-82.7, 21.16, -15.08]} scale={0}>
                <T.Mesh
                  name="particle073_sand_particle_0"
                  geometry={gltf.nodes.particle073_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle072" position={[-84.66, 20.3, -30.7]} scale={0}>
                <T.Mesh
                  name="particle072_sand_particle_0"
                  geometry={gltf.nodes.particle072_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle071" position={[-85.25, 21.58, -5.16]} scale={0}>
                <T.Mesh
                  name="particle071_sand_particle_0"
                  geometry={gltf.nodes.particle071_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle070" position={[-73.79, 19.85, -26.82]} scale={0}>
                <T.Mesh
                  name="particle070_sand_particle_0"
                  geometry={gltf.nodes.particle070_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle069" position={[-75.96, 19.72, 5.37]} scale={0}>
                <T.Mesh
                  name="particle069_sand_particle_0"
                  geometry={gltf.nodes.particle069_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle068" position={[-68.93, 20.72, 3.33]} scale={0}>
                <T.Mesh
                  name="particle068_sand_particle_0"
                  geometry={gltf.nodes.particle068_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle067" position={[-89.79, 21.16, 1.23]} scale={0}>
                <T.Mesh
                  name="particle067_sand_particle_0"
                  geometry={gltf.nodes.particle067_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle066" position={[-58.02, 19.8, 4.5]} scale={0}>
                <T.Mesh
                  name="particle066_sand_particle_0"
                  geometry={gltf.nodes.particle066_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle065" position={[-56.81, 20.78, 8.52]} scale={0}>
                <T.Mesh
                  name="particle065_sand_particle_0"
                  geometry={gltf.nodes.particle065_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle064" position={[-91.18, 17.38, 5.27]} scale={0}>
                <T.Mesh
                  name="particle064_sand_particle_0"
                  geometry={gltf.nodes.particle064_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle063" position={[-64.41, 17.84, -10.01]} scale={0}>
                <T.Mesh
                  name="particle063_sand_particle_0"
                  geometry={gltf.nodes.particle063_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle062" position={[-88, 20.86, -15.01]} scale={0}>
                <T.Mesh
                  name="particle062_sand_particle_0"
                  geometry={gltf.nodes.particle062_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle061" position={[-56.18, 20.18, 11.94]} scale={0}>
                <T.Mesh
                  name="particle061_sand_particle_0"
                  geometry={gltf.nodes.particle061_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle060" position={[-80.02, 19.32, -8.87]} scale={0}>
                <T.Mesh
                  name="particle060_sand_particle_0"
                  geometry={gltf.nodes.particle060_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle059" position={[-69.54, 21.06, 6.7]} scale={0}>
                <T.Mesh
                  name="particle059_sand_particle_0"
                  geometry={gltf.nodes.particle059_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle058" position={[-81.08, 19.9, -8.08]} scale={0}>
                <T.Mesh
                  name="particle058_sand_particle_0"
                  geometry={gltf.nodes.particle058_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle057" position={[-63.34, 18.56, -10.34]} scale={0}>
                <T.Mesh
                  name="particle057_sand_particle_0"
                  geometry={gltf.nodes.particle057_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle056" position={[-68.54, 19.06, -24.21]} scale={0}>
                <T.Mesh
                  name="particle056_sand_particle_0"
                  geometry={gltf.nodes.particle056_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle055" position={[-56.38, 19.71, 13.14]} scale={0}>
                <T.Mesh
                  name="particle055_sand_particle_0"
                  geometry={gltf.nodes.particle055_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle054" position={[-61.95, 14.29, 15.38]} scale={0}>
                <T.Mesh
                  name="particle054_sand_particle_0"
                  geometry={gltf.nodes.particle054_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle053" position={[-94.62, 21.92, -4.68]} scale={0}>
                <T.Mesh
                  name="particle053_sand_particle_0"
                  geometry={gltf.nodes.particle053_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle052" position={[-95.34, 19.51, -22.43]} scale={0}>
                <T.Mesh
                  name="particle052_sand_particle_0"
                  geometry={gltf.nodes.particle052_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle051" position={[-83.6, 19.31, -18.99]} scale={0}>
                <T.Mesh
                  name="particle051_sand_particle_0"
                  geometry={gltf.nodes.particle051_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle050" position={[-86.83, 14.8, 15.15]} scale={0}>
                <T.Mesh
                  name="particle050_sand_particle_0"
                  geometry={gltf.nodes.particle050_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle049" position={[-76.37, 20.54, 9.34]} scale={0}>
                <T.Mesh
                  name="particle049_sand_particle_0"
                  geometry={gltf.nodes.particle049_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle048" position={[-56.82, 21.45, -8.47]} scale={0}>
                <T.Mesh
                  name="particle048_sand_particle_0"
                  geometry={gltf.nodes.particle048_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle047" position={[-78.91, 20.03, 8.51]} scale={0}>
                <T.Mesh
                  name="particle047_sand_particle_0"
                  geometry={gltf.nodes.particle047_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle046" position={[-79.54, 19.75, 8.18]} scale={0}>
                <T.Mesh
                  name="particle046_sand_particle_0"
                  geometry={gltf.nodes.particle046_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle045" position={[-78.29, 20.39, -20.58]} scale={0}>
                <T.Mesh
                  name="particle045_sand_particle_0"
                  geometry={gltf.nodes.particle045_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle044" position={[-83.27, 21.72, -12.43]} scale={0}>
                <T.Mesh
                  name="particle044_sand_particle_0"
                  geometry={gltf.nodes.particle044_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle043" position={[-57.8, 20.81, 10.79]} scale={0}>
                <T.Mesh
                  name="particle043_sand_particle_0"
                  geometry={gltf.nodes.particle043_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle042" position={[-65.19, 14.26, 15.44]} scale={0}>
                <T.Mesh
                  name="particle042_sand_particle_0"
                  geometry={gltf.nodes.particle042_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle041" position={[-65.92, 20.64, 0.22]} scale={0}>
                <T.Mesh
                  name="particle041_sand_particle_0"
                  geometry={gltf.nodes.particle041_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle040" position={[-88.36, 21.35, -21.54]} scale={0}>
                <T.Mesh
                  name="particle040_sand_particle_0"
                  geometry={gltf.nodes.particle040_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle039" position={[-97.01, 19.48, -14.04]} scale={0}>
                <T.Mesh
                  name="particle039_sand_particle_0"
                  geometry={gltf.nodes.particle039_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle038" position={[-65.04, 22.18, 9.56]} scale={0}>
                <T.Mesh
                  name="particle038_sand_particle_0"
                  geometry={gltf.nodes.particle038_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle037" position={[-63.95, 17.43, -29.6]} scale={0}>
                <T.Mesh
                  name="particle037_sand_particle_0"
                  geometry={gltf.nodes.particle037_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle036" position={[-96.58, 20.32, -9.41]} scale={0}>
                <T.Mesh
                  name="particle036_sand_particle_0"
                  geometry={gltf.nodes.particle036_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle035" position={[-65.44, 19.25, -5.99]} scale={0}>
                <T.Mesh
                  name="particle035_sand_particle_0"
                  geometry={gltf.nodes.particle035_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle034" position={[-95.07, 21.2, -8.96]} scale={0}>
                <T.Mesh
                  name="particle034_sand_particle_0"
                  geometry={gltf.nodes.particle034_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle033" position={[-100.21, 14.31, -1.35]} scale={0}>
                <T.Mesh
                  name="particle033_sand_particle_0"
                  geometry={gltf.nodes.particle033_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle032" position={[-53.96, 14.57, 12.33]} scale={0}>
                <T.Mesh
                  name="particle032_sand_particle_0"
                  geometry={gltf.nodes.particle032_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle031" position={[-70.94, 20.72, 5.48]} scale={0}>
                <T.Mesh
                  name="particle031_sand_particle_0"
                  geometry={gltf.nodes.particle031_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle030" position={[-92.21, 18.5, -21.78]} scale={0}>
                <T.Mesh
                  name="particle030_sand_particle_0"
                  geometry={gltf.nodes.particle030_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle029" position={[-76.87, 20.16, -23.1]} scale={0}>
                <T.Mesh
                  name="particle029_sand_particle_0"
                  geometry={gltf.nodes.particle029_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle028" position={[-95.18, 21.84, -4.93]} scale={0}>
                <T.Mesh
                  name="particle028_sand_particle_0"
                  geometry={gltf.nodes.particle028_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle027" position={[-93.56, 21.56, -0.17]} scale={0}>
                <T.Mesh
                  name="particle027_sand_particle_0"
                  geometry={gltf.nodes.particle027_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle026" position={[-85.25, 21.58, -5.16]} scale={0}>
                <T.Mesh
                  name="particle026_sand_particle_0"
                  geometry={gltf.nodes.particle026_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle025" position={[-86.69, 21.79, -4.1]} scale={0}>
                <T.Mesh
                  name="particle025_sand_particle_0"
                  geometry={gltf.nodes.particle025_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle024" position={[-90.23, 21.19, -20.41]} scale={0}>
                <T.Mesh
                  name="particle024_sand_particle_0"
                  geometry={gltf.nodes.particle024_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle023" position={[-58.34, 18.66, -19.38]} scale={0}>
                <T.Mesh
                  name="particle023_sand_particle_0"
                  geometry={gltf.nodes.particle023_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle022" position={[-56.21, 20.42, 5.82]} scale={0}>
                <T.Mesh
                  name="particle022_sand_particle_0"
                  geometry={gltf.nodes.particle022_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle021" position={[-94.75, 19.29, -21.54]} scale={0}>
                <T.Mesh
                  name="particle021_sand_particle_0"
                  geometry={gltf.nodes.particle021_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle020" position={[-57.06, 21.44, -5.56]} scale={0}>
                <T.Mesh
                  name="particle020_sand_particle_0"
                  geometry={gltf.nodes.particle020_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle019" position={[-83.59, 20.09, 9.75]} scale={0}>
                <T.Mesh
                  name="particle019_sand_particle_0"
                  geometry={gltf.nodes.particle019_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle018" position={[-96.79, 19.52, -14.7]} scale={0}>
                <T.Mesh
                  name="particle018_sand_particle_0"
                  geometry={gltf.nodes.particle018_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle017" position={[-56.23, 19.11, 0.92]} scale={0}>
                <T.Mesh
                  name="particle017_sand_particle_0"
                  geometry={gltf.nodes.particle017_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle016" position={[-93.13, 21.99, -8.59]} scale={0}>
                <T.Mesh
                  name="particle016_sand_particle_0"
                  geometry={gltf.nodes.particle016_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle015" position={[-70.78, 19.82, -27.78]} scale={0}>
                <T.Mesh
                  name="particle015_sand_particle_0"
                  geometry={gltf.nodes.particle015_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle014" position={[-63.32, 21.1, 10.43]} scale={0}>
                <T.Mesh
                  name="particle014_sand_particle_0"
                  geometry={gltf.nodes.particle014_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle013" position={[-81.08, 19.9, -8.08]} scale={0}>
                <T.Mesh
                  name="particle013_sand_particle_0"
                  geometry={gltf.nodes.particle013_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle012" position={[-97.55, 21.47, 0.99]} scale={0}>
                <T.Mesh
                  name="particle012_sand_particle_0"
                  geometry={gltf.nodes.particle012_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle011" position={[-99.05, 20.15, -27.8]} scale={0}>
                <T.Mesh
                  name="particle011_sand_particle_0"
                  geometry={gltf.nodes.particle011_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle010" position={[-80.33, 20.52, 10.4]} scale={0}>
                <T.Mesh
                  name="particle010_sand_particle_0"
                  geometry={gltf.nodes.particle010_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle009" position={[-93.79, 21.48, -1.3]} scale={0}>
                <T.Mesh
                  name="particle009_sand_particle_0"
                  geometry={gltf.nodes.particle009_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle008" position={[-62.78, 14.91, 15.39]} scale={0}>
                <T.Mesh
                  name="particle008_sand_particle_0"
                  geometry={gltf.nodes.particle008_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle007" position={[-85.55, 21.24, -20.17]} scale={0}>
                <T.Mesh
                  name="particle007_sand_particle_0"
                  geometry={gltf.nodes.particle007_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle006" position={[-72.75, 20.79, 7.05]} scale={0}>
                <T.Mesh
                  name="particle006_sand_particle_0"
                  geometry={gltf.nodes.particle006_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle005" position={[-82.45, 20.68, -23.07]} scale={0}>
                <T.Mesh
                  name="particle005_sand_particle_0"
                  geometry={gltf.nodes.particle005_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle004" position={[-62.59, 18.58, -11.62]} scale={0}>
                <T.Mesh
                  name="particle004_sand_particle_0"
                  geometry={gltf.nodes.particle004_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle003" position={[-91.37, 14.2, 15.19]} scale={0}>
                <T.Mesh
                  name="particle003_sand_particle_0"
                  geometry={gltf.nodes.particle003_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle002" position={[-75.97, 14.62, -33.22]} scale={0}>
                <T.Mesh
                  name="particle002_sand_particle_0"
                  geometry={gltf.nodes.particle002_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="particle001" position={[-73.8, 20.95, 9.2]} scale={0}>
                <T.Mesh
                  name="particle001_sand_particle_0"
                  geometry={gltf.nodes.particle001_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group
                name="Armature004"
                position={[-81.65, 21.85, -26.08]}
                rotation={[-1.54, -0.12, -2.55]}
                scale={0.05}
              >
                <T.Group name="Object_5">
                  <T is={gltf.nodes._rootJoint} />
                  <T.Group
                    name="Object_99"
                    position={[-81.79, 22.88, -26.08]}
                    rotation={[-1.54, -0.12, -2.55]}
                    scale={0.05}
                  />
                  <T.Group
                    name="Object_101"
                    position={[-81.65, 21.85, -26.08]}
                    rotation={[-1.54, -0.12, -2.55]}
                    scale={0.05}
                  />
                  <T.SkinnedMesh
                    name="Object_100"
                    geometry={gltf.nodes.Object_100.geometry}
                    material={gltf.materials['birds.001']}
                    skeleton={gltf.nodes.Object_100.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_102"
                    geometry={gltf.nodes.Object_102.geometry}
                    material={gltf.materials['birds.001']}
                    skeleton={gltf.nodes.Object_102.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="canyon_animal_vulture_wings001"
                position={[-81.79, 22.88, -26.08]}
                rotation={[-1.54, -0.12, -2.55]}
                scale={0.05}
              />
              <T.Group
                name="canyonl_animal_vulture_body"
                position={[-81.65, 21.85, -26.08]}
                rotation={[-1.54, -0.12, -2.55]}
                scale={0.05}
              />
              <T.Group
                name="Armature005"
                position={[-80.02, 19.57, -22.38]}
                rotation={[-Math.PI / 2, 0, -0.96]}
                scale={0.06}
              >
                <T.Group name="Object_106">
                  <T is={gltf.nodes._rootJoint_1} />
                  <T.Group
                    name="Object_200"
                    position={[-80.07, 20.97, -22.35]}
                    rotation={[-Math.PI / 2, 0, -0.96]}
                    scale={0.06}
                  />
                  <T.Group
                    name="Object_202"
                    position={[-80.02, 19.57, -22.38]}
                    rotation={[-Math.PI / 2, 0, -0.96]}
                    scale={0.06}
                  />
                  <T.SkinnedMesh
                    name="Object_201"
                    geometry={gltf.nodes.Object_201.geometry}
                    material={gltf.materials['birds.001']}
                    skeleton={gltf.nodes.Object_201.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_203"
                    geometry={gltf.nodes.Object_203.geometry}
                    material={gltf.materials['birds.001']}
                    skeleton={gltf.nodes.Object_203.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="canyon_animal_vulture_wings002"
                position={[-80.07, 20.97, -22.35]}
                rotation={[-Math.PI / 2, 0, -0.96]}
                scale={0.06}
              />
              <T.Group
                name="canyonl_animal_vulture_body001"
                position={[-80.02, 19.57, -22.38]}
                rotation={[-Math.PI / 2, 0, -0.96]}
                scale={0.06}
              />
              <T.Group name="particle000" position={[-95.94, 21.64, -2.1]} scale={0}>
                <T.Mesh
                  name="particle000_sand_particle_0"
                  geometry={gltf.nodes.particle000_sand_particle_0.geometry}
                  material={gltf.materials.sand_particle}
                />
              </T.Group>
              <T.Group name="Field001" position={[-86.97, 32.43, 6.96]} rotation={[-Math.PI / 2, 0, 0]} />
              <T.Group name="Field" position={[-67.24, 26.17, -17.09]} rotation={[-2.49, -0.72, -0.6]} />
              <T.Group name="canyon_deco_stone_small01" position={[-61.74, 20.13, -3.25]}>
                <T.Mesh
                  name="canyon_deco_stone_small01_rocks_0"
                  geometry={gltf.nodes.canyon_deco_stone_small01_rocks_0.geometry}
                  material={gltf.materials.rocks}
                />
              </T.Group>
              <T.Group name="canyon_foliage01_leaves" position={[-64.12, 21.6, 0.25]}>
                <T.Mesh
                  name="canyon_foliage01_leaves_foliage_0"
                  geometry={gltf.nodes.canyon_foliage01_leaves_foliage_0.geometry}
                  material={gltf.materials.foliage}
                />
              </T.Group>
              <T.Group name="Cone010" position={[-86.45, 21.52, -4.4]} rotation={[Math.PI, -1.38, Math.PI]}>
                <T.Mesh
                  name="Cone010_senor_0"
                  geometry={gltf.nodes.Cone010_senor_0.geometry}
                  material={gltf.materials.senor}
                />
              </T.Group>
              <T.Group
                name="Armature003"
                position={[-67.24, 24.84, -10.88]}
                rotation={[-1.4, -0.11, -2.94]}
                scale={0.02}
              >
                <T.Group name="Object_615">
                  <T is={gltf.nodes._rootJoint_2} />
                  <T.Group
                    name="plom_small_Eye2"
                    position={[-20.37, -6.94, 79.21]}
                    rotation={[0.24, -0.08, 0.51]}
                    scale={1.01}
                  >
                    <T.Mesh
                      name="plom_small_Eye2_ele_canyon_sun_0"
                      geometry={gltf.nodes.plom_small_Eye2_ele_canyon_sun_0.geometry}
                      material={gltf.materials.ele_canyon_sun}
                    />
                  </T.Group>
                  <T.Group
                    name="Object_666"
                    position={[-67.24, 24.84, -10.88]}
                    rotation={[-1.4, -0.11, -2.94]}
                    scale={0.02}
                  />
                  <T.SkinnedMesh
                    name="Object_667"
                    geometry={gltf.nodes.Object_667.geometry}
                    material={gltf.materials['character_plom_big.001']}
                    skeleton={gltf.nodes.Object_667.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="plom_small"
                position={[-67.24, 24.84, -10.88]}
                rotation={[-1.4, -0.11, -2.94]}
                scale={0.02}
              />
              <T.Group
                name="gl_keycrate02"
                position={[-68.91, 23.25, -8.98]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.02}
              >
                <T.Mesh
                  name="gl_keycrate02_crate_0"
                  geometry={gltf.nodes.gl_keycrate02_crate_0.geometry}
                  material={gltf.materials.crate}
                />
              </T.Group>
              <T.Group
                name="Armature002"
                position={[-69.18, 14.62, -9.2]}
                rotation={[-Math.PI / 2, 0, 2.22]}
                scale={0.03}
              >
                <T.Group name="Object_672">
                  <T is={gltf.nodes._rootJoint_3} />
                  <T.Group name="Eye2" position={[9.25, -13.67, 172.78]} rotation={[1.99, -0.42, -3.02]} scale={0.91}>
                    <T.Mesh
                      name="Eye2_ele_canyon_sun_0"
                      geometry={gltf.nodes.Eye2_ele_canyon_sun_0.geometry}
                      material={gltf.materials.ele_canyon_sun}
                    />
                  </T.Group>
                  <T.Group
                    name="Object_739"
                    position={[-69.18, 14.62, -9.2]}
                    rotation={[-Math.PI / 2, 0, 2.22]}
                    scale={0.03}
                  />
                  <T.SkinnedMesh
                    name="Object_740"
                    geometry={gltf.nodes.Object_740.geometry}
                    material={gltf.materials['character_bismo_small.001']}
                    skeleton={gltf.nodes.Object_740.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="bismo_big"
                position={[-69.18, 14.62, -9.2]}
                rotation={[-Math.PI / 2, 0, 2.22]}
                scale={0.03}
              />
              <T.Group
                name="Plane"
                position={[-75.63, 17.07, -7.77]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={[23.23, 22.05, 20.33]}
              >
                <T.Mesh
                  name="Plane_sand_0"
                  geometry={gltf.nodes.Plane_sand_0.geometry}
                  material={gltf.materials.sand}
                />
              </T.Group>
              <T.Group name="Cube003" position={[-75.63, 8.31, -7.68]} rotation={[-Math.PI / 2, 0, 0]}>
                <T.Mesh
                  name="Cube003_rock_bottom_0"
                  geometry={gltf.nodes.Cube003_rock_bottom_0.geometry}
                  material={gltf.materials.rock_bottom}
                />
              </T.Group>
              <T.Group name="canyon_skull_lhorn" position={[-88.43, 17.58, -29.92]} rotation={[-0.47, -0.02, 0.38]}>
                <T.Mesh
                  name="canyon_skull_lhorn_skull_0"
                  geometry={gltf.nodes.canyon_skull_lhorn_skull_0.geometry}
                  material={gltf.materials.skull}
                />
              </T.Group>
              <T.Group name="canyon_sun01" position={[-104.26, 19.98, 22.62]}>
                <T.Mesh
                  name="canyon_sun01_ele_canyon_sun_0"
                  geometry={gltf.nodes.canyon_sun01_ele_canyon_sun_0.geometry}
                  material={gltf.materials.ele_canyon_sun}
                />
              </T.Group>
              <T.Group name="canyon_skull_lhorn_stump" position={[-235.46, -19.04, -9.61]}>
                <T.Mesh
                  name="canyon_skull_lhorn_stump_skull_0"
                  geometry={gltf.nodes.canyon_skull_lhorn_stump_skull_0.geometry}
                  material={gltf.materials.skull}
                />
              </T.Group>
              <T.Group name="canyon_skull_jaw" position={[-235.46, -19.04, -9.61]}>
                <T.Mesh
                  name="canyon_skull_jaw_Default-Material001_0"
                  geometry={gltf.nodes['canyon_skull_jaw_Default-Material001_0'].geometry}
                  material={gltf.materials['Default-Material.001']}
                />
              </T.Group>
              <T.Group name="Point007" position={[-65.13, 39.04, -17.22]}>
                <T.Group name="Object_755" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_756" />
                </T.Group>
              </T.Group>
              <T.Group
                name="Plane001"
                position={[-75.17, 13.77, -7.44]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[22.17, 22.77, 22.17]}
              >
                <T.Mesh
                  name="0"
                  geometry={gltf.nodes['0'].geometry}
                  material={gltf.materials.water}
                  morphTargetDictionary={gltf.nodes['0'].morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes['0'].morphTargetInfluences}
                />
              </T.Group>
              <T.Group name="Sun" position={[-94.42, 43.58, 2.74]} rotation={[-0.84, 0.35, 1.01]}>
                <T.Group name="Object_760" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_761" />
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
