<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\shifthappens.glb --root /models/ --printwidth 120 --precision 2
Author: Bijay (https://sketchfab.com/hembram1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shift-happens-in-the-dream-forest-diorama-29644c2623bb4027b1cc22b8696ce51a
Title: Shift Happens - in the Dream Forest Diorama
-->

<script>
  import {Group, LessEqualDepth} from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/shifthappens.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  $: $actions['Scene']?.play()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="RootNode_(gltf_orientation_matrix)_0" rotation={[-Math.PI / 2, 0, 0]}>
              <T.Group name="RootNode_(model_correction_matrix)_1">
                <T.Group name="69b8f327d21547778fe4aadf88c8a8a3fbx_2" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="_3">
                    <T.Group name="RootNode_4">
                      <T.Group name="particle074_5" position={[-1189.74, 2904.67, 724.61]} scale={0}>
                        <T.Group name="particle074_leaves_0_6">
                          <T.Mesh
                            name="Object_10"
                            geometry={gltf.nodes.Object_10.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle073_7" position={[-732.75, 3349.88, -1548.19]} scale={0}>
                        <T.Group name="particle073_leaves_0_8">
                          <T.Mesh
                            name="Object_13"
                            geometry={gltf.nodes.Object_13.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle072_9" position={[-2332.7, 3193.35, 184.08]} scale={0}>
                        <T.Group name="particle072_leaves_0_10">
                          <T.Mesh
                            name="Object_16"
                            geometry={gltf.nodes.Object_16.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle071_11" position={[-1070.03, 3241.3, -741.21]} scale={0}>
                        <T.Group name="particle071_leaves_0_12">
                          <T.Mesh
                            name="Object_19"
                            geometry={gltf.nodes.Object_19.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle070_13" position={[-2523.75, 3236.76, -376.53]} scale={0}>
                        <T.Group name="particle070_leaves_0_14">
                          <T.Mesh
                            name="Object_22"
                            geometry={gltf.nodes.Object_22.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle069_15" position={[-224.14, 2806.11, 952.1]} scale={0}>
                        <T.Group name="particle069_leaves_0_16">
                          <T.Mesh
                            name="Object_25"
                            geometry={gltf.nodes.Object_25.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle068_17" position={[-19.99, 2874.47, 615.09]} scale={0}>
                        <T.Group name="particle068_leaves_0_18">
                          <T.Mesh
                            name="Object_28"
                            geometry={gltf.nodes.Object_28.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle067_19" position={[-2839.65, 3188.2, -264.06]} scale={0}>
                        <T.Group name="particle067_leaves_0_20">
                          <T.Mesh
                            name="Object_31"
                            geometry={gltf.nodes.Object_31.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle066_21" position={[-2049.42, 3052.97, -151.97]} scale={0}>
                        <T.Group name="particle066_leaves_0_22">
                          <T.Mesh
                            name="Object_34"
                            geometry={gltf.nodes.Object_34.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle065_23" position={[-368.15, 2723.25, 844.2]} scale={0}>
                        <T.Group name="particle065_leaves_0_24">
                          <T.Mesh
                            name="Object_37"
                            geometry={gltf.nodes.Object_37.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle064_25" position={[-867.41, 2637.66, 1379.37]} scale={0}>
                        <T.Group name="particle064_leaves_0_26">
                          <T.Mesh
                            name="Object_40"
                            geometry={gltf.nodes.Object_40.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle063_27" position={[-884.97, 2963.25, -773.9]} scale={0}>
                        <T.Group name="particle063_leaves_0_28">
                          <T.Mesh
                            name="Object_43"
                            geometry={gltf.nodes.Object_43.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle062_29" position={[-1471.77, 2992.41, -1324.85]} scale={0}>
                        <T.Group name="particle062_leaves_0_30">
                          <T.Mesh
                            name="Object_46"
                            geometry={gltf.nodes.Object_46.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle061_31" position={[-501.83, 2531.04, 1227.9]} scale={0}>
                        <T.Group name="particle061_leaves_0_32">
                          <T.Mesh
                            name="Object_49"
                            geometry={gltf.nodes.Object_49.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle060_33" position={[-1447.24, 2909.46, -961.9]} scale={0}>
                        <T.Group name="particle060_leaves_0_34">
                          <T.Mesh
                            name="Object_52"
                            geometry={gltf.nodes.Object_52.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle059_35" position={[-3034.73, 2782.71, -266.4]} scale={0}>
                        <T.Group name="particle059_leaves_0_36">
                          <T.Mesh
                            name="Object_55"
                            geometry={gltf.nodes.Object_55.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle058_37" position={[-752.52, 2547.41, 680.54]} scale={0}>
                        <T.Group name="particle058_leaves_0_38">
                          <T.Mesh
                            name="Object_58"
                            geometry={gltf.nodes.Object_58.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle057_39" position={[-1243.44, 2778.38, -1195.65]} scale={0}>
                        <T.Group name="particle057_leaves_0_40">
                          <T.Mesh
                            name="Object_61"
                            geometry={gltf.nodes.Object_61.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle056_41" position={[-3069.35, 2646.15, -144.88]} scale={0}>
                        <T.Group name="particle056_leaves_0_42">
                          <T.Mesh
                            name="Object_64"
                            geometry={gltf.nodes.Object_64.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle055_43" position={[-2980.57, 2720.46, 407.58]} scale={0}>
                        <T.Group name="particle055_leaves_0_44">
                          <T.Mesh
                            name="Object_67"
                            geometry={gltf.nodes.Object_67.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle054_45" position={[-509.7, 2284.61, 964.51]} scale={0}>
                        <T.Group name="particle054_leaves_0_46">
                          <T.Mesh
                            name="Object_70"
                            geometry={gltf.nodes.Object_70.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle053_47" position={[-2314.27, 2538.75, 160.39]} scale={0}>
                        <T.Group name="particle053_leaves_0_48">
                          <T.Mesh
                            name="Object_73"
                            geometry={gltf.nodes.Object_73.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle052_49" position={[-1241.06, 2202.89, 1263.99]} scale={0}>
                        <T.Group name="particle052_leaves_0_50">
                          <T.Mesh
                            name="Object_76"
                            geometry={gltf.nodes.Object_76.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle051_51" position={[-937.34, 2313.72, 973.41]} scale={0}>
                        <T.Group name="particle051_leaves_0_52">
                          <T.Mesh
                            name="Object_79"
                            geometry={gltf.nodes.Object_79.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle050_53" position={[-1483.27, 2222.59, 1028.5]} scale={0}>
                        <T.Group name="particle050_leaves_0_54">
                          <T.Mesh
                            name="Object_82"
                            geometry={gltf.nodes.Object_82.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle049_55" position={[-857.22, 2194.05, 236.15]} scale={0}>
                        <T.Group name="particle049_leaves_0_56">
                          <T.Mesh
                            name="Object_85"
                            geometry={gltf.nodes.Object_85.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle048_57" position={[-1809.36, 2238.25, 1133.31]} scale={0}>
                        <T.Group name="particle048_leaves_0_58">
                          <T.Mesh
                            name="Object_88"
                            geometry={gltf.nodes.Object_88.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle047_59" position={[-3054.46, 2362.64, -410.05]} scale={0}>
                        <T.Group name="particle047_leaves_0_60">
                          <T.Mesh
                            name="Object_91"
                            geometry={gltf.nodes.Object_91.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle046_61" position={[-3654.42, 2422.79, 294.36]} scale={0}>
                        <T.Group name="particle046_leaves_0_62">
                          <T.Mesh
                            name="Object_94"
                            geometry={gltf.nodes.Object_94.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle045_63" position={[-1541.94, 2445.84, -1022.96]} scale={0}>
                        <T.Group name="particle045_leaves_0_64">
                          <T.Mesh
                            name="Object_97"
                            geometry={gltf.nodes.Object_97.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle044_65" position={[-1413.69, 2354.91, -1654.06]} scale={0}>
                        <T.Group name="particle044_leaves_0_66">
                          <T.Mesh
                            name="Object_100"
                            geometry={gltf.nodes.Object_100.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle043_67" position={[-3039.8, 2304.69, -590.95]} scale={0}>
                        <T.Group name="particle043_leaves_0_68">
                          <T.Mesh
                            name="Object_103"
                            geometry={gltf.nodes.Object_103.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle042_69" position={[-913.79, 2013.05, 1138.57]} scale={0}>
                        <T.Group name="particle042_leaves_0_70">
                          <T.Mesh
                            name="Object_106"
                            geometry={gltf.nodes.Object_106.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle041_71" position={[-3028.67, 2224.48, -136.12]} scale={0}>
                        <T.Group name="particle041_leaves_0_72">
                          <T.Mesh
                            name="Object_109"
                            geometry={gltf.nodes.Object_109.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle040_73" position={[-1153.88, 3361.23, -1031.08]} scale={0}>
                        <T.Group name="particle040_leaves_0_74">
                          <T.Mesh
                            name="Object_112"
                            geometry={gltf.nodes.Object_112.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle039_75" position={[-2836.55, 3263.79, 551.69]} scale={0}>
                        <T.Group name="particle039_leaves_0_76">
                          <T.Mesh
                            name="Object_115"
                            geometry={gltf.nodes.Object_115.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle038_77" position={[-2390.16, 3268.06, 735.49]} scale={0}>
                        <T.Group name="particle038_leaves_0_78">
                          <T.Mesh
                            name="Object_118"
                            geometry={gltf.nodes.Object_118.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle037_79" position={[-1944.51, 3269.84, 752.48]} scale={0}>
                        <T.Group name="particle037_leaves_0_80">
                          <T.Mesh
                            name="Object_121"
                            geometry={gltf.nodes.Object_121.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle036_81" position={[-553.87, 3361.23, -801.01]} scale={0}>
                        <T.Group name="particle036_leaves_0_82">
                          <T.Mesh
                            name="Object_124"
                            geometry={gltf.nodes.Object_124.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle035_83" position={[-921.93, 2918.78, 837.1]} scale={0}>
                        <T.Group name="particle035_leaves_0_84">
                          <T.Mesh
                            name="Object_127"
                            geometry={gltf.nodes.Object_127.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle034_85" position={[324.35, 2943.81, 688.66]} scale={0}>
                        <T.Group name="particle034_leaves_0_86">
                          <T.Mesh
                            name="Object_130"
                            geometry={gltf.nodes.Object_130.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle033_87"
                        position={[-944.35, 2922.38, 1503.7]}
                        rotation={[-1.02, -0.23, 1.23]}
                        scale={19.91}
                      >
                        <T.Group name="particle033_leaves_0_88">
                          <T.Mesh
                            name="Object_133"
                            geometry={gltf.nodes.Object_133.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle032_89"
                        position={[-761.23, 2895.91, 1742.07]}
                        rotation={[-0.81, -0.31, -1.27]}
                        scale={46.35}
                      >
                        <T.Group name="particle032_leaves_0_90">
                          <T.Mesh
                            name="Object_136"
                            geometry={gltf.nodes.Object_136.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle031_91"
                        position={[-2819.31, 3288.73, 127.18]}
                        rotation={[0.7, 0.27, -1.46]}
                        scale={151.88}
                      >
                        <T.Group name="particle031_leaves_0_92">
                          <T.Mesh
                            name="Object_139"
                            geometry={gltf.nodes.Object_139.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle030_93"
                        position={[-698.25, 2865.28, 960.41]}
                        rotation={[-1.02, 0.8, -0.71]}
                        scale={157.04}
                      >
                        <T.Group name="particle030_leaves_0_94">
                          <T.Mesh
                            name="Object_142"
                            geometry={gltf.nodes.Object_142.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle029_95"
                        position={[93.61, 2794.45, 864.41]}
                        rotation={[-1.31, -1.09, 1.41]}
                        scale={195.63}
                      >
                        <T.Group name="particle029_leaves_0_96">
                          <T.Mesh
                            name="Object_145"
                            geometry={gltf.nodes.Object_145.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle028_97"
                        position={[2.83, 2876.57, 1229.37]}
                        rotation={[-2.25, -0.72, -3.07]}
                        scale={138.51}
                      >
                        <T.Group name="particle028_leaves_0_98">
                          <T.Mesh
                            name="Object_148"
                            geometry={gltf.nodes.Object_148.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle027_99"
                        position={[-554.31, 2863.01, 679.15]}
                        rotation={[0.68, 1.24, -2.33]}
                        scale={121.69}
                      >
                        <T.Group name="particle027_leaves_0_100">
                          <T.Mesh
                            name="Object_151"
                            geometry={gltf.nodes.Object_151.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle026_101"
                        position={[-1416.57, 3256.68, -1687.98]}
                        rotation={[2.76, -0.58, 0.17]}
                        scale={177.24}
                      >
                        <T.Group name="particle026_leaves_0_102">
                          <T.Mesh
                            name="Object_154"
                            geometry={gltf.nodes.Object_154.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle025_103"
                        position={[-406.29, 2778.74, 1410.32]}
                        rotation={[0.13, -1.15, -0.02]}
                        scale={168.82}
                      >
                        <T.Group name="particle025_leaves_0_104">
                          <T.Mesh
                            name="Object_157"
                            geometry={gltf.nodes.Object_157.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle024_105"
                        position={[-1437.06, 3075.66, -1654.63]}
                        rotation={[-1.38, -0.06, 3.03]}
                        scale={186.08}
                      >
                        <T.Group name="particle024_leaves_0_106">
                          <T.Mesh
                            name="Object_160"
                            geometry={gltf.nodes.Object_160.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle023_107"
                        position={[-217.71, 2720.73, 558.73]}
                        rotation={[-1.52, 0.15, 0.22]}
                        scale={300.99}
                      >
                        <T.Group name="particle023_leaves_0_108">
                          <T.Mesh
                            name="Object_163"
                            geometry={gltf.nodes.Object_163.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle022_109"
                        position={[-899.69, 2701.99, 813.08]}
                        rotation={[-2.42, -0.01, -1.61]}
                        scale={205.2}
                      >
                        <T.Group name="particle022_leaves_0_110">
                          <T.Mesh
                            name="Object_166"
                            geometry={gltf.nodes.Object_166.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle021_111"
                        position={[-862.85, 2704.34, 1751.72]}
                        rotation={[-1.56, -0.54, 0.64]}
                        scale={251.27}
                      >
                        <T.Group name="particle021_leaves_0_112">
                          <T.Mesh
                            name="Object_169"
                            geometry={gltf.nodes.Object_169.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle020_113"
                        position={[-1376.47, 2469.71, 392.92]}
                        rotation={[0.87, 0.82, 0.65]}
                        scale={237.16}
                      >
                        <T.Group name="particle020_leaves_0_114">
                          <T.Mesh
                            name="Object_172"
                            geometry={gltf.nodes.Object_172.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle019_115"
                        position={[-2326.32, 2890.7, 189.74]}
                        rotation={[-0.45, 0.06, -1.11]}
                        scale={219.47}
                      >
                        <T.Group name="particle019_leaves_0_116">
                          <T.Mesh
                            name="Object_175"
                            geometry={gltf.nodes.Object_175.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle018_117"
                        position={[-765.52, 2926.41, -1762.24]}
                        rotation={[-1.99, 0.86, -2.79]}
                        scale={185.66}
                      >
                        <T.Group name="particle018_leaves_0_118">
                          <T.Mesh
                            name="Object_178"
                            geometry={gltf.nodes.Object_178.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle017_119"
                        position={[-1616.87, 2543.07, 561.14]}
                        rotation={[-1.06, -0.6, 0.87]}
                        scale={298.43}
                      >
                        <T.Group name="particle017_leaves_0_120">
                          <T.Mesh
                            name="Object_181"
                            geometry={gltf.nodes.Object_181.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle016_121"
                        position={[-810.36, 2984.03, -1909.91]}
                        rotation={[1.55, 0.59, -2.68]}
                        scale={252.99}
                      >
                        <T.Group name="particle016_leaves_0_122">
                          <T.Mesh
                            name="Object_184"
                            geometry={gltf.nodes.Object_184.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle015_123"
                        position={[-2337, 2807.11, -114.14]}
                        rotation={[0.04, -0.08, 0.55]}
                        scale={130.91}
                      >
                        <T.Group name="particle015_leaves_0_124">
                          <T.Mesh
                            name="Object_187"
                            geometry={gltf.nodes.Object_187.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle014_125"
                        position={[-1136.48, 2436.01, 1162.33]}
                        rotation={[-0.97, -0.52, -2.31]}
                        scale={243.34}
                      >
                        <T.Group name="particle014_leaves_0_126">
                          <T.Mesh
                            name="Object_190"
                            geometry={gltf.nodes.Object_190.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle013_127"
                        position={[-619.34, 2402.84, 1520.81]}
                        rotation={[-2.03, -1.11, 2.01]}
                        scale={227.47}
                      >
                        <T.Group name="particle013_leaves_0_128">
                          <T.Mesh
                            name="Object_193"
                            geometry={gltf.nodes.Object_193.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle012_129"
                        position={[-2989.38, 2549.62, -118.85]}
                        rotation={[-1.77, -0.29, -1.67]}
                        scale={201}
                      >
                        <T.Group name="particle012_leaves_0_130">
                          <T.Mesh
                            name="Object_196"
                            geometry={gltf.nodes.Object_196.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle011_131"
                        position={[-2596.48, 2698.96, 392.37]}
                        rotation={[-0.97, -0.75, 0.53]}
                        scale={124.14}
                      >
                        <T.Group name="particle011_leaves_0_132">
                          <T.Mesh
                            name="Object_199"
                            geometry={gltf.nodes.Object_199.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle010_133"
                        position={[-1303.31, 2222.8, 1329.28]}
                        rotation={[0.73, -0.89, 0.13]}
                        scale={233.12}
                      >
                        <T.Group name="particle010_leaves_0_134">
                          <T.Mesh
                            name="Object_202"
                            geometry={gltf.nodes.Object_202.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle009_135"
                        position={[-3082.88, 2544.47, -391.85]}
                        rotation={[1.95, -1.14, 2.04]}
                        scale={196.23}
                      >
                        <T.Group name="particle009_leaves_0_136">
                          <T.Mesh
                            name="Object_205"
                            geometry={gltf.nodes.Object_205.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle008_137"
                        position={[-948.5, 2238.1, 439.22]}
                        rotation={[1.7, -0.88, 2.2]}
                        scale={139.64}
                      >
                        <T.Group name="particle008_leaves_0_138">
                          <T.Mesh
                            name="Object_208"
                            geometry={gltf.nodes.Object_208.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle007_139"
                        position={[-1102.21, 2224.85, 1055.98]}
                        rotation={[-2.06, 0.18, -0.01]}
                        scale={128.57}
                      >
                        <T.Group name="particle007_leaves_0_140">
                          <T.Mesh
                            name="Object_211"
                            geometry={gltf.nodes.Object_211.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle006_141"
                        position={[-3198.17, 2396.82, -149.25]}
                        rotation={[1.34, -0.84, 1.85]}
                        scale={118.36}
                      >
                        <T.Group name="particle006_leaves_0_142">
                          <T.Mesh
                            name="Object_214"
                            geometry={gltf.nodes.Object_214.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle005_143"
                        position={[-1645.59, 2493.27, -1339.31]}
                        rotation={[-2.11, 0.53, -2.95]}
                        scale={173.13}
                      >
                        <T.Group name="particle005_leaves_0_144">
                          <T.Mesh
                            name="Object_217"
                            geometry={gltf.nodes.Object_217.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle004_145"
                        position={[-731.06, 2149.24, 773.97]}
                        rotation={[1, -0.43, -1.07]}
                        scale={142.43}
                      >
                        <T.Group name="particle004_leaves_0_146">
                          <T.Mesh
                            name="Object_220"
                            geometry={gltf.nodes.Object_220.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle003_147"
                        position={[-562.42, 1963.37, 643.49]}
                        rotation={[-2.1, -0.38, -2.65]}
                        scale={66.93}
                      >
                        <T.Group name="particle003_leaves_0_148">
                          <T.Mesh
                            name="Object_223"
                            geometry={gltf.nodes.Object_223.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle002_149"
                        position={[-1301.39, 1943.48, 1258.12]}
                        rotation={[0.46, 1.07, -2.72]}
                        scale={65.19}
                      >
                        <T.Group name="particle002_leaves_0_150">
                          <T.Mesh
                            name="Object_226"
                            geometry={gltf.nodes.Object_226.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="particle001_151"
                        position={[-3062.3, 2306.12, -24.81]}
                        rotation={[-3.04, -0.57, -0.5]}
                        scale={11.46}
                      >
                        <T.Group name="particle001_leaves_0_152">
                          <T.Mesh
                            name="Object_229"
                            geometry={gltf.nodes.Object_229.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="particle000_153" position={[-3540.31, 2387.31, -65.24]} scale={0}>
                        <T.Group name="particle000_leaves_0_154">
                          <T.Mesh
                            name="Object_232"
                            geometry={gltf.nodes.Object_232.geometry}
                            material={gltf.materials.leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="Cube_156"
                        position={[-2516.1, 1774.77, -77.21]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      >
                        <T.Group name="Cube_forest_leaves_0_157">
                          <T.Mesh
                            name="Object_235"
                            geometry={gltf.nodes.Object_235.geometry}
                            material={gltf.materials.forest_leaves}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="trees_158"
                        position={[-1672.74, 1560.03, -606.56]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      >
                        <T.Group name="trees_forest_trees_0_159">
                          <T.Mesh
                            name="Object_238"
                            geometry={gltf.nodes.Object_238.geometry}
                            material={gltf.materials.forest_trees}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="bismo_small_Eye2_160"
                        position={[-2551.62, 2078.82, 837.66]}
                        rotation={[-1.63, 0.04, -1.31]}
                        scale={[2.26, 3.16, 3.16]}
                      >
                        <T.Group name="bismo_small_Eye2_character_eyes_BIGblue_0_161">
                          <T.Mesh
                            name="Object_241"
                            geometry={gltf.nodes.Object_241.geometry}
                            material={gltf.materials.character_eyes_BIGblue}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="bismo_small_162"
                        position={[-2532.34, 1915.54, 890.1]}
                        rotation={[-1.74, -0.04, -2.1]}
                        scale={2.03}
                      >
                        <T.Group name="bismo_small_Material001_0_163">
                          <T.Mesh
                            name="Object_244"
                            geometry={gltf.nodes.Object_244.geometry}
                            material={gltf.materials['Material.001']}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group
                        name="plom_big_164"
                        position={[-3139.81, 1567.72, -416.78]}
                        rotation={[-1.24, 0.14, -2.83]}
                        scale={2.79}
                      >
                        <T.Group name="plom_big_plom_big_0_165">
                          <T.Mesh
                            name="Object_247"
                            geometry={gltf.nodes.Object_247.geometry}
                            material={gltf.materials.plom_big}
                          />
                        </T.Group>
                        <T.Group
                          name="plom_big_Eye2_166"
                          position={[16.73, 18.86, 0]}
                          rotation={[0.08, 0, Math.PI / 2]}
                        >
                          <T.Group name="plom_big_Eye2_character_eyes_0_167">
                            <T.Mesh
                              name="Object_250"
                              geometry={gltf.nodes.Object_250.geometry}
                              material={gltf.materials.character_eyes}
                            />
                          </T.Group>
                        </T.Group>
                        <T.Group
                          name="plom_big_Eye1_168"
                          position={[-4.27, 22.16, -0.24]}
                          rotation={[0.08, 0, Math.PI / 2]}
                        >
                          <T.Group name="plom_big_Eye1_character_eyes_0_169">
                            <T.Mesh
                              name="Object_253"
                              geometry={gltf.nodes.Object_253.geometry}
                              material={gltf.materials.character_eyes}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="bismo_small_Eye1_170" position={[-2552.77, 2083.34, 856.35]} scale={100}>
                        <T.Group name="bismo_small_Eye1_Default-Material_0_171">
                          <T.Mesh
                            name="Object_256"
                            geometry={gltf.nodes.Object_256.geometry}
                            material={gltf.materials['Default-Material']}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="water_172" position={[-2527.76, 1067.39, -1264.76]} scale={[121, 100, 120]}>
                        <T.Group name="0_173">
                          <T.Mesh
                            name="mesh_83"
                            geometry={gltf.nodes.mesh_83.geometry}
                            material={gltf.materials.ele_forest_water_dynamic}
                            morphTargetDictionary={gltf.nodes.mesh_83.morphTargetDictionary}
                            morphTargetInfluences={gltf.nodes.mesh_83.morphTargetInfluences}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="forest_grass_03_(9)_174" position={[-3773.39, 1639.83, -413.28]} scale={100}>
                        <T.Group name="forest_grass_03_(9)_grass_0_175">
                          <T.Mesh
                            name="Object_262"
                            geometry={gltf.nodes.Object_262.geometry}
                            material={gltf.materials.grass}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="terrain_176" position={[-1975.87, 1564.18, -212.22]} scale={100}>
                        <T.Group name="terrain_floor_0_177">
                          <T.Mesh
                            name="Object_265"
                            geometry={gltf.nodes.Object_265.geometry}
                            material={gltf.materials.floor}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="forest_fox_sleeping_178" position={[-2466.01, 1712.37, 647.9]} scale={100}>
                        <T.Group name="forest_fox_sleeping_fox_white_new_0_179">
                          <T.Mesh
                            name="Object_268"
                            geometry={gltf.nodes.Object_268.geometry}
                            material={gltf.materials.fox_white_new}
                          />
                        </T.Group>
                      </T.Group>
                      <T.Group name="canyon_mountains02_(3)_180" position={[-745.65, 1688.95, 2027.13]} scale={100}>
                        <T.Group name="canyon_mountains02_(3)_rock_0_181">
                          <T.Mesh
                            name="Object_271"
                            geometry={gltf.nodes.Object_271.geometry}
                            material={gltf.materials.rock}
                          />
                        </T.Group>
                      </T.Group>
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
