<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 D:\Source\leapy\static\models\yesbtn.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { spring } from 'svelte/motion'

  export const ref = new Group()

 

  const gltf = useGltf('/models/yesbtn.glb')

  export let opacity;
  
  let modelRef;

  gltf.then((model) => {
    modelRef = model;
    modelRef.materials['Material.003'].transparent = true;
    modelRef.materials['Material.002'].transparent = true;
  });

   $: if(modelRef) {
    modelRef.materials['Material.003'].opacity = opacity;
    modelRef.materials['Material.002'].opacity = opacity;
   } 

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-2.37, 1.38, -1]}>
      <T.Mesh geometry={gltf.nodes.Cube001.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Cube001_1.geometry} material={gltf.materials['Material.003']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
